composeApp/build.gradle.kts
- Add explicit input file tracking for MacosApi.swift
- Ensure task recompiles when Swift source changes
- Use file objects for better path handling
- Add directory creation step to prevent build failures
- Update commandLine to use file object paths
This change ensures that the compileSwift task properly detects changes in the Swift source file and recompiles when necessary, improving the reliability of the build process.
close #1613
=> :construction_worker: Improve Gradle task for Swift compilation

composeApp/src/desktopMain/kotlin/com/crosspaste/os/linux/api/XFixes.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/LinuxPasteboardService.kt
- Update clipboard event detection to use clipboardAtom.toLong() instead of hardcoded value (0x145L)
- Add selectionNotify.clear() to prevent memory leaks
This fix addresses a Linux-specific issue where clipboard changes were not being detected correctly due to system-dependent atom values. It also prevents potential memory leaks in the X11 event handling process.
close #1620
=> :bug: [Linux] Fix clipboard detection and memory leak in pasteboard service

composeApp/src/desktopMain/kotlin/com/crosspaste/app/WinAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/os/windows/api/User32.kt
- Resolve issue where GetForegroundWindow API returns incorrect window
- Adjust timing of API call relative to showMainWindow flag
- Prevent self-referential window capture affecting paste functionality
The bug occurred because GetForegroundWindow was called via JNA after setting showMainWindow = true, potentially returning our own search window instead of the intended previous application. This affected the accuracy of clipboard operations.
close #1650
=> :bug: Correct previous app info retrieval

composeApp/src/desktopMain/kotlin/com/crosspaste/sync/DesktopSyncManager.kt
=> :bug: Fix DesktopSyncManager exit exception issue

composeApp/src/desktopMain/kotlin/com/crosspaste/listen/KeyboardKeys.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/LinuxKeyboardKeys.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/MacKeyboardKeys.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/WindowsKeyboardKeys.kt
=> :bug: Add missing listener for backtick (`) key

composeApp/src/commonMain/kotlin/com/crosspaste/ui/search/PasteSearchView.kt
In scenarios where it's necessary to switch between items up and down, many software applications feature Ctrl+N and Ctrl+P keyboard shortcuts. This allows users to keep their hands on the main part of the keyboard (as opposed to moving their hands to use arrow keys), making it more user-friendly.
=> Add Ctrl+N and Ctrl+P shortcuts to search window

composeApp/src/commonMain/kotlin/com/crosspaste/dao/paste/PasteRealm.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/routing/PasteRouting.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/task/PullFileTaskExecutor.kt
1. Remove loading status on sync failure
2. Catch clipboard serialization exceptions
3. Skip hash deduplication when hash is empty
close #1762
=> :bug: Fix pasteboard sync bugs

composeApp/src/commonMain/kotlin/com/crosspaste/dao/sync/SyncRuntimeInfoDao.kt, composeApp/src/commonMain/kotlin/com/crosspaste/sync/SyncManager.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceConnectView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/dao/sync/SyncRuntimeInfoRealm.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/sync/DesktopDeviceManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/sync/DesktopSyncHandler.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/sync/DesktopSyncManager.kt
=> :bug: Update trusted device info based on listeners

composeApp/src/commonMain/kotlin/com/crosspaste/module/ModuleLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/html/ChromeModuleLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/html/DesktopChromeService.kt
=> :bug: Use chrome-headless-shell for HTML rendering without window creation

composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceVerifyView.kt
- Allow users to move focus to the previous input field when pressing backspace on an empty field
- Clear the content of the previous field when moving focus backwards
- Improve user experience by allowing easier correction of input errors
close #2091
=> :lipstick: Implement backspace functionality in DeviceVerifyView token input

composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/StoreSettingsContentView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/ColorUtils.desktop.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/utils/ColorUtilsTest.kt
- Fix hex color validation by adding strict length check (6 or 8 digits)
- Improve RGB/RGBA parsing with better whitespace handling
- Fix alpha value calculation using roundToInt instead of truncation
- Enhance RGBA alpha pattern to support all valid formats (0, 1, 0.x, 1.0)
- Add comprehensive unit tests for color format parsing and conversion
close #2152
=> :bug: Improve color format parsing and add conversion tests

composeApp/src/commonMain/kotlin/com/crosspaste/utils/CodecsUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/FileUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/StringUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/FileUtils.desktop.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/utils/MurmurHash3Test.kt
=> :bug: Avoid circular reference between fileUtils and CodecsUtils, which will cause compilation failure in iOS environment

composeApp/src/commonMain/kotlin/com/crosspaste/utils/CodecsUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/CodecsUtils.desktop.kt
=> :hammer: Base64 implementation using kotlin.io, better multiplatform equivalent implementation

composeApp/src/commonMain/kotlin/com/crosspaste/serializer/Base64ByteArraySerializer.kt, composeApp/src/commonMain/kotlin/com/crosspaste/serializer/PasteDataSerializer.kt, composeApp/src/commonMain/kotlin/com/crosspaste/serializer/PasteLabelRealmSetSerializer.kt, composeApp/src/commonMain/kotlin/com/crosspaste/serializer/RealmListSerializer.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/JsonUtils.desktop.kt
=> :bug: Use class instead of object for serialization to prevent iOS crashes

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppLaunch.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppLaunch.kt
Convert AppLaunch.launch() to a suspend function to support asynchronous operations. This is particularly useful for mobile clients where app launching often involves async initialization steps.
close #2286
=> :hammer: Make launch function suspendable

gradle/libs.versions.toml
=> :arrow_up: Bump compose-plugin from 1.7.1 to 1.7.3

app/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncHandler.kt, app/src/commonMain/kotlin/com/crosspaste/sync/MarketingSyncHandler.kt, app/src/commonMain/kotlin/com/crosspaste/sync/SyncHandler.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceVerifyView.kt
When attempting to connect a device for the first time from an attachment device, there was an issue where the verification code was not successfully displayed to the other party. This commit fixes this notification problem, ensuring that the verification code is properly shown during the initial connection process.
close #2461
=> :bug: Fix missing verification code on first device connection

app/src/commonMain/kotlin/com/crosspaste/app/AppControl.kt, app/src/commonMain/kotlin/com/crosspaste/net/routing/PasteRouting.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppControl.kt
This commit adds the suspend modifier to several methods in the AppControl interface, specifically:
isSendEnabled()
isReceiveEnabled()
completeSendOperation()
completeReceiveOperation()
Additionally, it fixes a critical bug where completeReceiveOperation() was not being properly called in the previous implementation, which could lead to incomplete operation handling and potential resource leaks.
close #2485
=> :bug: Add suspend modifiers and fix operation completion

app/src/commonMain/kotlin/com/crosspaste/ui/HomeMenuView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/ScreenContext.kt, app/src/commonMain/kotlin/com/crosspaste/ui/ScreenType.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/DesktopScreenProvider.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/MacTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/TabsView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopUISupport.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/devices/DeviceConnectContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/DesktopSettingsViewProvider.kt
- Changed ScreenType from an enum class to a sealed interface
- Created object implementations for each screen type
- Improves extensibility by making it easier to add new screen types
- Note: QR_SCANNER type from the original enum is not included in the new implementation as it was for mobile use only
close #2498
=> :hammer: Replace ScreenType enum with sealed interface pattern

app/src/commonMain/kotlin/com/crosspaste/paste/item/PasteText.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/TextPreviewView.kt
=> :sparkles: Add method to PasteText for reading first 256 characters for preview, avoiding lag from loading large data

app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopFilesTypePlugin.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopImageTypePlugin.kt
=> :bug: Fix image file clipboard transfer to web applications

app/src/commonMain/kotlin/com/crosspaste/paste/item/HtmlPasteItem.kt, app/src/commonMain/kotlin/com/crosspaste/paste/item/PasteHtml.kt, app/src/commonMain/kotlin/com/crosspaste/paste/item/PasteRtf.kt, app/src/commonMain/kotlin/com/crosspaste/paste/item/RtfPasteItem.kt, app/src/commonMain/kotlin/com/crosspaste/ui/model/GeneralPasteSearchViewModel.kt, app/src/commonMain/kotlin/com/crosspaste/ui/model/MarketingPasteData.kt, app/src/commonMain/kotlin/com/crosspaste/ui/model/MarketingPasteSearchViewModel.kt, app/src/commonMain/kotlin/com/crosspaste/ui/model/PasteSearchViewModel.kt, app/src/desktopMain/kotlin/com/crosspaste/DesktopCrossPasteModule.kt
=> :sparkles: Add marketing definition support to search interface

app/src/commonMain/kotlin/com/crosspaste/ui/base/HighlightedCard.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/MobileExpandView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/PastePreviewItemView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/settings/NetSettingsContentView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/settings/PasteboardSettingsContentView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/settings/StoreSettingsContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/TabsView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/ExpandView.desktop.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/MainSettingsContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/SetStoragePathView.kt
=> :lipstick: Create the display effect for HighlightedCard prompt UI

app/src/commonMain/kotlin/com/crosspaste/ui/base/ExpandViewProvider.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopExpandViewProvider.kt
=> :bug: Fix ExpandView java.lang.AbstractMethodError

app/src/commonMain/kotlin/com/crosspaste/app/AppInfo.kt, app/src/commonMain/kotlin/com/crosspaste/db/sync/SyncRuntimeInfoDao.kt, app/src/commonMain/kotlin/com/crosspaste/db/task/TaskDao.kt, app/src/commonMain/kotlin/com/crosspaste/dto/sync/EndpointInfo.kt, app/src/commonMain/kotlin/com/crosspaste/dto/sync/SyncInfo.kt, app/src/commonMain/kotlin/com/crosspaste/sync/QRCodeGenerator.kt, app/src/commonMain/kotlin/com/crosspaste/ui/settings/NetSettingsContentView.kt, app/src/commonMain/kotlin/com/crosspaste/utils/TaskUtils.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/TextPreviewView.kt, app/src/desktopTest/kotlin/com/crosspaste/serializer/SerializerTest.kt
=> :hammer: Remove redundant encodeToString import, iOS side has fixed the mandatory import issue

app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/MacTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/MainWindow.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/WindowsTrayView.kt
=> :hammer: Refactor main window position control logic

app/build.gradle.kts, gradle/libs.versions.toml, settings.gradle.kts
=> :construction_worker: Add hot reload support using compose-hot-reload

.github/workflows/claude-code-review.yml
=> :construction_worker: Switch Claude review to comment-triggered workflow

app/src/commonMain/kotlin/com/crosspaste/ui/paste/PasteDataScope.kt
1. Remove javaClass to support multi-platform
2. Remove internal modifier to enable reuse on mobile platforms
close #3131
=>  :bug: Fix PasteDataScopeImpl implementation
