composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppLaunch.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/MacAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/endpoint/DesktopEndpointInfoFactory.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/image/DesktopFileExtLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/os/macos/MacAppUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/os/macos/MacDeviceUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/os/macos/MacPasteUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/os/macos/MacosKeychainHelper.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/os/macos/api/MacosApi.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/MacTrayView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/DeviceUtils.desktop.kt
=> :bug: Fix memory leak issue in MacosApi

composeApp/src/commonMain/kotlin/com/crosspaste/config/AppConfig.kt, composeApp/src/commonMain/kotlin/com/crosspaste/dao/paste/PasteData.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/item/PasteFiles.kt, composeApp/src/commonMain/kotlin/com/crosspaste/path/PathProvider.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/dao/paste/PasteRealm.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/item/FilesPasteItem.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/item/ImagesPasteItem.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/FilesTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/realm/RealmManagerImpl.kt
Use reference copy for files exceeding auto-backup size limit
close #1624
close #1625
=> :sparkles: Add default configuration to limit auto-backup file size

composeApp/src/commonMain/kotlin/com/crosspaste/config/AppConfig.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/FileUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/dao/paste/PasteRealm.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/FilesTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/FileUtils.desktop.kt
=> :sparkles: Add default configuration to limit file size for auto-sync across devices

composeApp/src/commonMain/kotlin/com/crosspaste/paste/PasteboardService.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/TransferableProducer.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/ShortcutKeysView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortKeysAction.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortcutKeys.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/AbstractPasteboardService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/DesktopTransferableProducer.kt, composeApp/src/desktopMain/resources/i18n/en.properties, composeApp/src/desktopMain/resources/i18n/es.properties, composeApp/src/desktopMain/resources/i18n/jp.properties, composeApp/src/desktopMain/resources/i18n/zh.properties, composeApp/src/desktopMain/resources/shortcut_keys/Linux.properties, composeApp/src/desktopMain/resources/shortcut_keys/Macos.properties, composeApp/src/desktopMain/resources/shortcut_keys/Windows.properties
=> :lipstick: Add shortcut for pasting plain text

composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/detail/HtmlToImageDetailView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/detail/PasteFilesDetailView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/detail/PasteImagesDetailView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/detail/PasteTextDetailView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/detail/PasteUrlDetailView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/FilesPreviewView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/HtmlToImagePreviewView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/ImagesPreviewView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/PastePreviewItemView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/TextPreviewView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/UrlPreviewView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/search/DetialPasteDataView.kt
=> :sparkles: Add double-click quick copy feature

composeApp/src/commonMain/kotlin/com/crosspaste/dao/paste/PasteDao.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/HomeView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/TabsView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/PasteTooltipAreaView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/dao/paste/PasteRealm.kt, composeApp/src/desktopMain/resources/i18n/en.properties, composeApp/src/desktopMain/resources/i18n/es.properties, composeApp/src/desktopMain/resources/i18n/jp.properties, composeApp/src/desktopMain/resources/i18n/zh.properties
=> :sparkles: Add one-click clear clipboard feature excluding favorites

composeApp/src/desktopMain/resources/i18n/en.properties, composeApp/src/desktopMain/resources/i18n/es.properties, composeApp/src/desktopMain/resources/i18n/jp.properties, composeApp/src/desktopMain/resources/i18n/zh.properties
=> :bug: Add translations for Clean successful

composeApp/src/desktopMain/kotlin/com/crosspaste/app/LinuxAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/MacAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/WinAppWindowManager.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/app/TestWindowManager.kt
=> :bug: Resolve delayed PrevAppName refresh in search UI

composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/DialogButtonsView.kt
=> :lipstick: Resolve text overflow in DialogButtonsView buttons

composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/NetSettingsView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/PasteboardSettingsView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/SetStoragePathView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/SettingItemView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/SettingsView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/StoreSettingsView.kt
=> :recycle: Abstract SettingItemView component

composeApp/src/desktopMain/kotlin/com/crosspaste/path/DesktopAppPathProvider.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/path/DesktopUserDataPathProvider.kt
=> :bug: Ensure platform is initialized before use

.github/scripts/validateAndUpdateVersion.js, .github/workflows/build-release.yml
1. Adopt new tag naming convention to support Sparkle incremental updates
2. Upgrade setup-java action to v4
3. Update Conveyor to version 15.0
4. Refine revision setting script logic
close #1664
=> :construction_worker: Improve build script and update dependencies

composeApp/src/desktopMain/resources/app-urls.properties
=> :bug: Fix check-metadata-url address for version checking

composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/SettingsView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/config/DefaultConfigManager.kt
=> :bug: Fix pasteboard listener and sync encryption UI refresh

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppLock.kt, composeApp/src/commonMain/kotlin/com/crosspaste/app/AppWindowManager.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/CrossPasteGrantAccessibilityPermissions.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/AbstractAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppLaunch.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/os/macos/api/MacosApi.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/MacTrayView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/WindowsTrayView.kt
=> :sparkles: Implement automatic UI display on first app launch

composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppStartUpService.kt
=> :bug: Prevent Dev/Test version from modifying boot startup flag

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppFileType.kt, composeApp/src/commonMain/kotlin/com/crosspaste/path/UserDataPathProvider.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/UISupport.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/detail/HtmlToImageDetailView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/FileUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/path/DesktopUserDataPathProvider.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopUISupport.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/FileUtils.desktop.kt
=> :bug: Reimplemented opening file copies in temporary directory

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppTokenService.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/TokenView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppTokenService.kt
=> :lipstick: token and QR code refresh to add progress bar

README.md, README.zh-CN.md
=> :memo: Add badges for technology stack and project information

README.md, README.zh-CN.md
=> :memo: Add official website link to README

composeApp/src/commonMain/kotlin/com/crosspaste/utils/SystemProperty.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/net/DesktopProxy.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/SystemProperty.desktop.kt.kt
=> :bug: Correctly detect user proxy settings

composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/NetSettingsView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/NetUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/ValueProvider.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/NetUtils.desktop.kt
=> :bug: Accurately obtain local ip address

.github/workflows/build-release.yml
=> :bug: Fix conflicting step IDs in GitHub Actions workflow

composeApp/src/commonMain/kotlin/com/crosspaste/path/AppPathProvider.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/path/DesktopAppPathProvider.kt, composeApp/src/desktopMain/kotlin/org/openqa/selenium/manager/SeleniumManager.kt
=> :bug: Fix incorrect path setting for selenium-manager

.github/scripts/updateKnownGoodVersionsWithDownloads.js
=> :construction_worker: Preserve complete download info in mirrored Chrome `known-good-versions-with-downloads.json` config

composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/UrlTypePlugin.kt
=> :chart_with_upwards_trend: [win] Prevent exceptions from URL checks printing

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppUpdateService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppUpdateService.kt
=> :bug: Resolve bug in application version check

composeApp/build.gradle.kts, composeApp/src/desktopMain/kotlin/org/openqa/selenium/manager/SeleniumManager.kt
=> :bug: Fix MSIX package validation failure for Microsoft Store build

composeApp/src/commonMain/kotlin/com/crosspaste/path/PathProvider.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/FileUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/FilesToImagesPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/FilesTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/path/DesktopUserDataPathProvider.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/FileUtils.desktop.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/utils/FileUtilsTest.kt
=> :hammer: Refactor file operations using okio for cross-platform compatibility and add desktop unit tests

composeApp/src/commonMain/kotlin/com/crosspaste/dao/paste/PasteData.kt, composeApp/src/commonMain/kotlin/com/crosspaste/dao/paste/PasteItem.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/PasteCollector.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/item/PasteFile.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/plugin/type/TextUpdater.kt, composeApp/src/commonMain/kotlin/com/crosspaste/presist/FileInfoTree.kt, composeApp/src/commonMain/kotlin/com/crosspaste/serializer/PasteDataSerializer.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/edit/PasteTextEditView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/CodecsUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/FileUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/dao/paste/PasteRealm.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/item/FilesPasteItem.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/item/HtmlPasteItem.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/item/ImagesPasteItem.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/item/TextPasteItem.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/item/UrlPasteItem.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/FilesToImagesPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/GenerateUrlPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/MultFilesPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/MultiImagesPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/FilesTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/HtmlTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/ImageTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/TextTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/UrlTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/realm/RealmManagerImpl.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/CodecsUtils.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/FileUtils.desktop.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/serializer/SerializerTest.kt
=> :zap: Replace MD5 with Murmur3 128-bit hash for improved large file performance

composeApp/src/desktopMain/kotlin/org/openqa/selenium/manager/SeleniumManager.kt
=> :bug: [win] Fix selenium-manager path recognition error

composeApp/build.gradle.kts, composeApp/src/commonMain/kotlin/com/crosspaste/utils/CodecsUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/CodecsUtils.desktop.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/utils/CodecsUtilsTest.kt, gradle/libs.versions.toml
=> :bug: Fix hash encoding and refactor it to implement as cross-platform code

composeApp/build.gradle.kts, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindow.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt
=> :bug: application crash on system tray icon click sigsegv error

composeApp/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt
=> :bug: [Linux] Fix main window display position

README.md, README.zh-CN.md
=> :memo: Remove description of first-time chromeDriver / chrome-headless-shell download from README

composeApp/build.gradle.kts
=> :bug: Use IPv4 and disable IPv6 addresses

composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceConnectView.kt, composeApp/src/desktopMain/resources/i18n/en.properties, composeApp/src/desktopMain/resources/i18n/es.properties, composeApp/src/desktopMain/resources/i18n/jp.properties, composeApp/src/desktopMain/resources/i18n/zh.properties
=> :sparkles: Support active refreshing of device connections

.github/scripts/validateAndUpdateVersion.js
=> :bug: Fix version number parsing in GitHub Actions workflow

composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceConnectView.kt
=> :lipstick: Enhance device connection refresh interaction

composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/sync/DesktopSyncHandler.kt
=> :bug: Fix incomplete exit process

composeApp/src/desktopMain/kotlin/com/crosspaste/html/DesktopChromeService.kt
=> :bug: Set ChromeServiceModule files as executable before execution

composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt
=> :bug: Fix UI blocking during application exit

composeApp/src/commonMain/kotlin/com/crosspaste/app/EndpointInfoFactory.kt, composeApp/src/commonMain/kotlin/com/crosspaste/dto/sync/EndpointInfo.kt, composeApp/src/commonMain/kotlin/com/crosspaste/dto/sync/SyncInfo.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopEndpointInfoFactory.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/net/DesktopPasteBonjourService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/net/DesktopPasteServer.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/net/DesktopSyncInfoFactory.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/routing/SyncRouting.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/sync/DesktopQRCodeGenerator.kt
=> :hammer: Remove endpoint package and refactor code

composeApp/src/desktopMain/kotlin/com/crosspaste/os/linux/api/WMCtrl.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/os/windows/html/HtmlCodec.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/ImageTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/sync/DesktopQRCodeGenerator.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/task/CleanPasteTaskExecutor.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/DateUtils.desktop.kt
=> :hammer: Internationalize project by converting Chinese comments to English

composeApp/src/commonMain/kotlin/com/crosspaste/path/PlatformUserDataPathProvider.kt, composeApp/src/commonMain/kotlin/com/crosspaste/path/UserDataPathProvider.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/path/DesktopUserDataPathProvider.kt
=> :hammer: refactor UserDataPathProvider: use cross-platform APIs

composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/SetStoragePathView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppInfoFactory.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppRestartService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/DesktopGlobalListener.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/net/DesktopPasteBonjourService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/signal/IdentityKeyStore.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/MacTrayView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/WindowsTrayView.kt
=> :hammer: standardize logger creation within respective classes

composeApp/src/commonMain/kotlin/com/crosspaste/utils/TxtRecordUtils.kt
=> :hammer: Refactor TxtRecordUtils for multi-platform support

composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt
=> :zap: Hide tray immediately on application exit

composeApp/src/commonMain/kotlin/com/crosspaste/dao/paste/PasteDao.kt, composeApp/src/commonMain/kotlin/com/crosspaste/dao/paste/PasteRealm.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/CurrentPaste.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/PasteboardService.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/TransferableProducer.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortKeysAction.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/AbstractPasteboardService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/DesktopCurrentPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/DesktopPasteSearchService.kt
=> :zap: Prioritize matching pasteboard when searching and pasting

composeApp/src/desktopMain/kotlin/com/crosspaste/os/windows/api/User32.kt
=> :bug: [Win] Fix mouse cursor displacement to bottom-right when invoking search window

composeApp/src/commonMain/kotlin/com/crosspaste/presist/OneFilePersist.kt
=> :bug: Fix bug in OneFilePersist where kClass.java impl was bound to JVM

composeApp/src/commonMain/kotlin/com/crosspaste/net/routing/SyncRouting.kt
=> :bug: Fix the issue of strong binding to JVM String in SyncRouting

composeApp/src/desktopMain/kotlin/com/crosspaste/paste/LinuxPasteboardService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/MacosPasteboardService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/WindowsPasteboardService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/ControlUtils.desktop.kt
=> :bug: Correct AtomicLong reference in ControlUtils

composeApp/src/commonMain/kotlin/com/crosspaste/image/AbstractFileExtImageLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/image/DesktopFileExtLoader.kt
=> :hammer: Abstract AbstractFileExtImageLoader for multi-platform reuse

composeApp/src/commonMain/kotlin/com/crosspaste/paste/DefaultPasteSyncProcessManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt
=> :hammer: Refactor DesktopPasteSyncProcessManager to commonMain for multi-platform reuse

composeApp/src/desktopMain/kotlin/com/crosspaste/paste/MacosPasteboardService.kt
=> :bug: Fix bug where app reads pasteboard on first launch to get CrossPaste source

composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopEndpointInfoFactory.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/html/DesktopChromeService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/FilesToImagesPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/MultFilesPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/MultiImagesPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/EncryptUtils.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/serializer/SerializerTest.kt
=> :hammer: Standardize using 'get' method to obtain utils classes

composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/NotificationManager.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceConnectView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/PasteMenuView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/PastePreviewItemView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/TabsView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopNotificationManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/DetialPasteDataView.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/ui/base/TestNotificationManager.kt
=> :hammer: Merge two interfaces of NotificationManager, no need for repetition

composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/FilesTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/HtmlTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/ImageTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/TextTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/UrlTypePlugin.kt
=> :hammer: Constants in PasteTypePlugin are now uniformly recorded within the default companion object

.github/ISSUE_TEMPLATE/feature.yml, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/ImageTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/DetailPasteDataView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/PasteSearchView.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/i18n/GlobalCopywriterTest.kt
=> :hammer: Fix typos throughout the project

composeApp/src/commonMain/kotlin/com/crosspaste/image/ImageWriter.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/image/DesktopFileExtLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/image/DesktopImageWriter.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/image/WebpImageWriter.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/ImageTypePlugin.kt
=> :hammer: Refactor ImageWriter into a generic interface for reuse on mobile platforms

composeApp/build.gradle.kts, composeApp/src/commonMain/kotlin/com/crosspaste/utils/CodecsUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/FileUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/MurmurHash3.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/CodecsUtils.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/FileUtils.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/MurmurHash3.desktop.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/utils/MurmurHash3Test.kt, gradle/libs.versions.toml
=> :sparkles: Integrate MurmurHash3 source code and add StreamingMurmurHash3

composeApp/src/desktopMain/kotlin/com/crosspaste/paste/MacosPasteboardService.kt
=> :bug: [Mac] Skip listening to initial pasteboard change

composeApp/src/desktopMain/kotlin/com/crosspaste/image/DesktopThumbnailLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/platform/macos/MacAppUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/platform/macos/api/MacosApi.kt, composeApp/src/desktopMain/swift/MacosApi.swift
=> :sparkles: Implement native macOS API for thumbnail generation

composeApp/src/commonMain/kotlin/com/crosspaste/net/clientapi/SyncClientApi.kt, composeApp/src/commonMain/kotlin/com/crosspaste/sync/QRCodeGenerator.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/edit/PasteTextEditView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/CodecsUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/TxtRecordUtils.kt
=> :hammer: Refactor toByteArray to be platform-independent in commonMain

composeApp/build.gradle.kts
=> :construction_worker: Enable expect/actual classes in JVM target with "-Xexpect-actual-classes" flag

composeApp/src/commonMain/kotlin/com/crosspaste/utils/FileUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/FileUtils.desktop.kt
=> :hammer: Allow null ext in createRandomFileName for multi-platform reuse

composeApp/src/desktopMain/kotlin/com/crosspaste/net/DesktopProxy.kt
=> :bug: Fix bug in verifying if proxy is working

composeApp/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindow.kt
=> :bug: Fix the issue where the hover effect of the search button on the main UI is affected by TokenView

composeApp/src/desktopMain/kotlin/com/crosspaste/utils/NetUtils.desktop.kt
=> :bug: Relax restrictions on private IP addresses

composeApp/src/commonMain/kotlin/com/crosspaste/utils/DeviceUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopEndpointInfoFactory.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/DeviceUtils.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/NetUtils.desktop.kt
=> :hammer: Optimize NetUtils and DeviceUtils

composeApp/src/desktopMain/resources/crosspaste-version.properties
=> :bookmark: Update version to 1.0.10

CHANGELOG.md, README.md, README.zh-CN.md
=> :memo: Update changelog / download to 1.0.10

composeApp/build.gradle.kts, composeApp/src/commonMain/kotlin/com/crosspaste/utils/NetUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/ValueProvider.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/NetUtils.desktop.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/utils/NetworkUtilsTest.kt
=> :white_check_mark: Add unit tests for NetworkUtils

composeApp/src/commonMain/kotlin/com/crosspaste/net/routing/BaseSyncRouting.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/routing/PasteRouting.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/routing/PullRouting.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/routing/SyncRouting.kt
=> :hammer: Refactor routing impl for early returns and reduced nesting

composeApp/src/commonMain/kotlin/com/crosspaste/utils/PlatformLock.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/ValueProvider.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/NetUtils.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/PlatformLock.desktop.kt
=> :bug: Improve network interface handling and error management

composeApp/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortcutKeysLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/settings/ShortcutKeysScreen.desktop.kt, composeApp/src/desktopMain/resources/i18n/en.properties, composeApp/src/desktopMain/resources/i18n/es.properties, composeApp/src/desktopMain/resources/i18n/jp.properties, composeApp/src/desktopMain/resources/i18n/zh.properties
=> :sparkles: Add support for unassigned shortcuts

composeApp/src/desktopMain/kotlin/com/crosspaste/image/DesktopImageDataLoader.kt
=> :bug: Fix repeated reading of ImageBitmap

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppSize.kt, composeApp/src/commonMain/kotlin/com/crosspaste/app/AppWindowManager.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/SingleImagePreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppSize.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppTokenService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/LinuxAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/MacAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/WinAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/html/DesktopChromeService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortKeysAction.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/DesktopPasteSearchService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindow.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteSearchWindow.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/MacTrayView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/WindowsTrayView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopNotificationManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/PasteboardScreen.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteDetailView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/PasteSearchView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/SearchListView.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/app/AppWindowManagerTest.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/app/TestWindowManager.kt
1. Replace Compose mutableStateOf with StateFlow for better state management
2. Consolidate UI dimension constants into a separate class for improved organization
3. Fix window position flickering issue when clicked
close #1971
=> :hammer: Refactor application window implementation

composeApp/src/commonMain/kotlin/com/crosspaste/image/coil/ImageItems.kt, composeApp/src/commonMain/kotlin/com/crosspaste/image/coil/ImageLoaders.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/PasteTypeIconView.kt
=> :bug: Fix issue with appSourceFetcher retrieving application icons

composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/HtmlToImageView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/HtmlToImagePreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/HtmlToImageDetailView.kt
=> :bug: Fix alignment of HTML preview pasteboard

composeApp/build.gradle.kts
=> :construction_worker: Remove the task for extracting selenium-manager, as it is no longer used

composeApp/src/commonMain/kotlin/com/crosspaste/image/coil/ImageLoaders.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/IconView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/PasteTypeIconView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/HtmlToImageView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/SingleFilePreviewView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/SingleImagePreviewView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/CoilUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteFilesDetailView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteImagesDetailView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/CoilUtils.desktop.kt
=> :hammer: Refactor PlatformContext retrieval for multi-platform compatibility

composeApp/src/commonMain/kotlin/com/crosspaste/image/coil/UserImageFetcher.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/routing/PullRouting.kt, composeApp/src/commonMain/kotlin/com/crosspaste/path/UserDataPathProvider.kt, composeApp/src/commonMain/kotlin/com/crosspaste/presist/OneFilePersist.kt, composeApp/src/commonMain/kotlin/com/crosspaste/realm/paste/PasteRealm.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/PullIconTaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/SingleImagePreviewView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/FileUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/OkioPathExtension.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortcutKeys.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopIconStyle.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopUISupport.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/FileUtils.desktop.kt
=> :hammer: Use expect/actual for FileSystem to support multiple platforms

composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/PasteShimmer.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteShimmer.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PrePreviewView.kt
=> :hammer: Abstract PasteShimmer to allow independent impl of shimmer effects on different platforms

composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteImagesDetailView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/HtmlToImagePreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteSpecificPreviewContentView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PrePreviewView.kt
=> :hammer: Replace unnecessary BoxWithConstraints with Box

composeApp/src/desktopMain/resources/crosspaste-version.properties
=> :bookmark: Update version to 1.0.11

composeApp/src/commonMain/kotlin/com/crosspaste/ui/HomeMenuView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/LocalComposition.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceDetailContentView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/SingleFilePreviewView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/DeviceUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/ResourceUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopEndpointInfoFactory.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/config/DefaultConfigManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteScreen.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/MacTrayView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/TabsView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/WindowDecoration.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/devices/DevicesScreen.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/edit/PasteTextEditContentView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteMenuView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/DesktopResourceUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/DeviceUtils.desktop.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/i18n/GlobalCopywriterTest.kt
=> :hammer: Refactor commonMain for multiplatform compatibility

composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppSize.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/PasteSearchView.kt
=> :bug: Fix UI issue where the bottom bar was not displayed in the search window

composeApp/src/commonMain/kotlin/com/crosspaste/image/AbstractFaviconLoader.kt, composeApp/src/commonMain/kotlin/com/crosspaste/image/AbstractThumbnailLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/image/DesktopFaviconLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/image/DesktopThumbnailLoader.kt
=> :hammer: Abstract AbstractFaviconLoader and AbstractThumbnailLoader to allow maximum reuse across multiple platforms

composeApp/src/commonMain/kotlin/com/crosspaste/clean/CleanPasteScheduler.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/CleanPasteTaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/DeletePasteTaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/Html2ImageTaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/PullIconTaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/SyncPasteTaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/TaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/TaskUtils.kt
=> :hammer: Use direct import instead of referencing through package

composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/HtmlToImageView.kt
=> :lipstick: Add proper padding when displaying text due to HTML rendering failure

composeApp/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortcutKeysListener.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortcutKeysLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/KeyboardKeys.kt
=> :bug: Fix issue where shortcut key order affects simulated paste

composeApp/src/commonMain/kotlin/com/crosspaste/html/HtmlRenderingService.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/Html2ImageTaskExecutor.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/html/DesktopHtmlRenderingService.kt
=> :hammer: Rename ChromeService to HtmlRenderingService

composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/LinuxAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/MacAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/WinAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortKeysAction.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/DesktopPasteSearchService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/platform/linux/api/X11Api.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/platform/macos/MacAppUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/platform/macos/api/MacosApi.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/platform/windows/api/User32.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/platform/windows/api/WndEnumProc.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteSpecificPreviewView.kt, composeApp/src/desktopMain/swift/MacosApi.swift, composeApp/src/desktopTest/kotlin/com/crosspaste/app/TestWindowManager.kt
=> :lipstick: Support cross-application paste by double-clicking pasteboard item in main window

CHANGELOG.md, README.md, README.zh-CN.md
=> :memo: Update changelog / download to 1.0.11

composeApp/src/commonMain/kotlin/com/crosspaste/html/HtmlRenderingService.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/Html2ImageTaskExecutor.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/html/DesktopHtmlRenderingService.kt
=> :hammer: Modify HtmlRenderingService API to support asynchronous HTML rendering

composeApp/src/commonMain/kotlin/com/crosspaste/paste/plugin/process/PasteProcessPlugin.kt, composeApp/src/commonMain/kotlin/com/crosspaste/realm/paste/PasteRealm.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/DistinctPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/FilesToImagesPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/GenerateUrlPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/MultFilesPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/MultiImagesPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/RemoveFolderImagePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/SortPlugin.kt
=> :art: Modify plugin interface to add pasteboard source parameter

composeApp/src/commonMain/kotlin/com/crosspaste/paste/plugin/type/FilesTypePlugin.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/plugin/type/HtmlTypePlugin.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/plugin/type/ImageTypePlugin.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/plugin/type/TextTypePlugin.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/plugin/type/UrlTypePlugin.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/Html2ImageTaskExecutor.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopFilesTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopHtmlTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopImageTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopTextTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopUrlTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/plugin/office/OfficeHtmlPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/edit/PasteTextEditContentView.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/serializer/SerializerTest.kt
=> :sparkles: Enhance desktop plugin class implementation

composeApp/src/commonMain/kotlin/com/crosspaste/utils/FileUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/RemoveHtmlImagePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/SortPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopImageTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopUISupport.kt
=> :sparkles: Store only image type when copying browser images, remove HTML type

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppWindowManager.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/UISupport.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/PasteMenuService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/TabsView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopUISupport.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/PasteContextMenuRepresentation.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/FilesPreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/HtmlToImagePreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/ImagesPreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteContextMenuView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteMenuView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/TextPreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/UrlPreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/DetailPasteDataView.kt
=> :sparkles: Add separate right-click menu for pasteboard

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppWindowManager.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/HomeMenuView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/LocalComposition.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/UISupport.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceConnectView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceDetailContentView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DevicesView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppWindowManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/PasteMenuService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteScreen.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/MacTrayView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/TabsView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/WindowDecoration.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopUISupport.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/devices/DeviceConnectView.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/devices/DevicesScreen.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/edit/PasteTextEditContentView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteMenuView.kt
=> :hammer: Improve screen routing implementation

doc/en/Concepts.md, doc/zh/Concepts.md
=> :sparkles: Update pasteboard concept, add RTF type support

composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/TransparentBackgroundView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteImagesDetailView.kt
=> :zap: Enhance Transparency Checkerboard for improved image background

README.md, README.zh-CN.md
=> :memo: Update README.md

composeApp/src/commonMain/kotlin/com/crosspaste/realm/paste/PasteRealm.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/rendering/DesktopRenderingHelper.kt
=> :bug: Fix simple code smells

composeApp/src/commonMain/kotlin/com/crosspaste/config/ReadWriteConfig.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/PasteServer.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt
=> :memo: Implement ReadWriteConfig to decouple services from specific configurations, facilitating the creation of unit tests

composeApp/src/commonMain/kotlin/com/crosspaste/ui/CrossPasteTheme.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/DesktopThemeDetector.kt
=> :fire: Remove theme listener interface as it's unnecessary; Compose UI will automatically recompose based on state

composeApp/src/commonMain/kotlin/com/crosspaste/ui/CrossPasteTheme.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/ThemeBackground.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/ThemeDetector.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/CrossPasteGrantAccessibilityPermissions.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/MenuView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/PasteTitleView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/AddDeviceManuallyView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceDetailContentView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceStateView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/NearbyDeviceView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindow.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/WindowsTrayView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/devices/DeviceConnectView.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/devices/SyncDeviceView.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteMenuView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/PasteSearchView.kt
=> :hammer: Refactor theme implementation

composeApp/src/commonMain/kotlin/com/crosspaste/ui/CrossPasteScreen.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/HomeScreen.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindow.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindowContent.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteScreen.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/HomeScreen.desktop.kt
=> :hammer: Improve UI Reusability and multiplatform Compatibility

composeApp/src/commonMain/kotlin/com/crosspaste/image/coil/FileExtFetcher.kt, composeApp/src/commonMain/kotlin/com/crosspaste/image/coil/UserImageFetcher.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/TelnetHelper.kt, composeApp/src/commonMain/kotlin/com/crosspaste/path/UserDataPathProvider.kt, composeApp/src/commonMain/kotlin/com/crosspaste/realm/sync/SyncRuntimeInfoRealm.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/SyncPasteTaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/SetStoragePathView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/RetryUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppLaunch.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppStartUpService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppTokenService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/config/DefaultConfigManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/i18n/I18n.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/image/DesktopThumbnailLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortcutKeys.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortcutKeysLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/module/AbstractModuleLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/net/DesktopProxy.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/processs/GenerateUrlPlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopImageTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/platform/linux/FreedesktopUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/platform/linux/LinuxPlatform.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/rendering/ChromeModuleLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/AppEnvUtils.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/DeviceUtils.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/NetUtils.desktop.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/dao/store/SessionBuilderTest.kt
1. Use _ to replace ignorable exceptions
2. Use KLogger interface instead of string concatenation to print exception messages
3. Unify Dispatcher style
close #2083
=> :hammer: Optimize code style

composeApp/src/desktopMain/resources/crosspaste-version.properties
=> :bookmark: Update version to 1.0.12

conveyor.conf
=> :bug: Fix the path for referencing resource files in conveyor

composeApp/src/commonMain/kotlin/com/crosspaste/net/SyncRefresher.kt, composeApp/src/commonMain/kotlin/com/crosspaste/sync/DeviceManager.kt, composeApp/src/commonMain/kotlin/com/crosspaste/sync/SyncHandler.kt, composeApp/src/commonMain/kotlin/com/crosspaste/sync/SyncManager.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/DialogService.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DevicesView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindowContent.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/devices/DeviceConnectView.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/devices/DevicesScreen.desktop.kt
=> :zap: Improve device sync logic

gradle/libs.versions.toml
=> :arrow_up: Bump compose-plugin from 1.7.0-rc01 to 1.7.0

composeApp/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/DesktopResourceUtils.kt
=> :bug: Fix icon path error issue on Linux

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppInfo.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/AboutContentView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/MainSettingsView.kt
=> :lipstick: Add About item to main settings menu

composeApp/src/commonMain/kotlin/com/crosspaste/ui/CrossPasteTheme.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/ThemeDetector.kt
=> :sparkles: Enable ThemeDetector to get current ColorScheme

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppTokenService.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/routing/SyncRouting.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/TokenView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppTokenService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindowContent.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/devices/QRScreen.desktop.kt
=> :hammer: Make AppTokenService multiplatform reusable

composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceDetailContentView.kt
=> :art: Wrap DeviceConnectView inside Column for better layout isolation

composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt
=> :bug: Initialize copywriter and notificationManager in configManager

composeApp/src/commonMain/kotlin/com/crosspaste/paste/TransferableConsumer.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/DesktopTransferableConsumer.kt
=> :hammer: Move common pasteboard consumption logic to TransferableConsumer for multiplatform reuse

composeApp/src/commonMain/kotlin/com/crosspaste/paste/PasteboardService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/AbstractPasteboardService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/LinuxPasteboardService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/MacosPasteboardService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/WindowsPasteboardService.kt
=> :hammer: Extract remote pasteboard listening service to common interface

CHANGELOG.md, README.md, README.zh-CN.md
=> :memo: Update changelog / download to 1.0.12

composeApp/src/commonMain/kotlin/com/crosspaste/sync/QRCodeGenerator.kt
1. Use project's JSON serializer consistently
2. Add QR code data decoding functionality
close #2132
=> :sparkles: Enhance QR code generation and parsing

composeApp/src/commonMain/kotlin/com/crosspaste/sync/SyncHandler.kt, composeApp/src/commonMain/kotlin/com/crosspaste/sync/SyncManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt
1. Remove ViewModel dependency for future responsibility segregation
2. Replace unnecessary async with launch for better coroutine usage
3. Use dependency injection for TokenCache access
close #2137
=> :hammer: Optimize SyncManager implementation

composeApp/src/commonMain/kotlin/com/crosspaste/paste/PasteMenuService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/DesktopPasteMenuService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/FilesPreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/HtmlToImagePreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/ImagesPreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteMenuView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/RtfToImagePreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/TextPreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/UrlPreviewView.kt
=> :hammer: Extract PasteMenuService interface for multiplatform reuse

composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/SingleImagePreviewView.kt
=> :bug: Correct image cropping and centering on Android platform

composeApp/src/commonMain/kotlin/com/crosspaste/paste/NoneTransferData.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/plugin/type/PasteTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/DesktopWriteTransferable.kt
=> :sparkles: Add NoneTransferData to handle invalid data

doc/en/Concepts.md, doc/zh/Concepts.md
Commit 17c8845826129c79930e5993c46b97854b4e228b moved the location of `SortPlugin.kt`. This PR adjusts sources to changes.
=> 📝 Update `SortPlugin.kt` reference

composeApp/src/commonMain/kotlin/com/crosspaste/paste/plugin/type/ColorTypePlugin.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/UISupport.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopColorTypePlugin.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopUISupport.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/ColorPreviewView.kt
=> :sparkles: Add support for updating color palette

composeApp/src/commonMain/kotlin/com/crosspaste/ui/model/PasteDataViewModel.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/PasteboardScreen.desktop.kt
=> :zap: Improve pasteboard loading logic

composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/PasteSearchView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/SearchInputView.kt
=> :hammer: Refactor search input into separate component

composeApp/src/commonMain/kotlin/com/crosspaste/realm/RealmManager.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt
=> :bug: Actively close Realm database when exiting the app to ensure data persistence

composeApp/src/desktopMain/resources/crosspaste-version.properties
=> :memo: Update version to 1.0.13

composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/ImagesPreviewView.kt
=> :bug: Fix regression issue with image type pasteboard display

README.md, README.zh-CN.md
=> :memo: Add tech blog links to README

composeApp/src/commonMain/kotlin/com/crosspaste/net/PasteClient.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/TelnetHelper.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/clientapi/PullClientApi.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/clientapi/SendPasteClientApi.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/clientapi/SyncClientApi.kt, composeApp/src/commonMain/kotlin/com/crosspaste/sync/SyncHandler.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/PullFileTaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/PullIconTaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/SyncPasteTaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/AddDeviceManuallyView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/RequestUtils.kt
=> :hammer: Optimize urlBuilder related interfaces to simplify usage

composeApp/src/commonMain/kotlin/com/crosspaste/app/EndpointInfoFactory.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/SyncInfoFactory.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/clientapi/SyncClientApi.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/routing/BaseSyncRouting.kt, composeApp/src/commonMain/kotlin/com/crosspaste/sync/SyncHandler.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/NetUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/NetUtils.desktop.kt
=> :zap: Optimize heartbeat performance by caching sync information to avoid repeated updates

composeApp/src/commonMain/kotlin/com/crosspaste/net/plugin/ClientEncryptPlugin.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/plugin/ServerDecryptionPluginFactory.kt
=> :hammer: Remove accidentally committed debug logs

composeApp/src/commonMain/kotlin/com/crosspaste/utils/FileUtils.kt
=> :bug: Resolve incorrect deletion of folder pasteboard

composeApp/src/commonMain/kotlin/com/crosspaste/paste/item/PasteCoordinate.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/SingleFilePreviewView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/SingleImagePreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteFilesDetailView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/FilesPreviewView.kt
=> :hammer: Refactor single file and image view

composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/FileIcon.kt
=> :hammer: Migrate FileIcon to Material 3 icon

composeApp/src/commonMain/kotlin/com/crosspaste/utils/CodecsUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/CodecsUtils.desktop.kt
=> :hammer: Move file hash algorithm to commonMain for multiplatform reuse

composeApp/src/commonMain/kotlin/com/crosspaste/utils/CodecsUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/CodecsUtils.desktop.kt
=> :hammer: Remove unused Base64 MIME encode/decode functions

composeApp/src/commonMain/kotlin/com/crosspaste/utils/CodecsUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/CodecsUtils.desktop.kt
=> :hammer: Move SHA256 algorithm to commonMain for multiplatform reuse

composeApp/src/commonMain/kotlin/com/crosspaste/serializer/RealmListSerializer.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/FileUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/FileUtils.desktop.kt
=> :hammer: Replace manual path separator with Okio Path API

composeApp/src/commonMain/kotlin/com/crosspaste/utils/FileUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/FileUtils.desktop.kt
=> :hammer: Make FileInfoTree creation multiplatform compatible

composeApp/src/commonMain/kotlin/com/crosspaste/dto/secure/PairingRequest.kt, composeApp/src/commonMain/kotlin/com/crosspaste/dto/secure/PairingResponse.kt, composeApp/src/commonMain/kotlin/com/crosspaste/dto/secure/TrustRequest.kt, composeApp/src/commonMain/kotlin/com/crosspaste/dto/secure/TrustResponse.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/item/PasteCoordinate.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/NetUtils.kt
=> :hammer: Replace javaClass comparison with platform-independent implementation in equals method

composeApp/src/commonMain/kotlin/com/crosspaste/image/AbstractThumbnailLoader.kt, composeApp/src/commonMain/kotlin/com/crosspaste/notification/NotificationManager.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/item/PasteColor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/sync/SyncHandler.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/ControlUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/CryptographyUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/DispatcherUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/WindowsPasteboardService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/ControlUtils.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/DispatcherUtils.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/FileUtils.desktop.kt
=> :bug: Fix commonMain implementation to support iOS compilation

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppVersionInfo.kt, composeApp/src/commonMain/kotlin/com/crosspaste/paste/item/ColorPasteItem.kt, composeApp/src/commonMain/kotlin/com/crosspaste/realm/paste/PasteCollection.kt, composeApp/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncManager.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/MurmurHash3.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppUpdateService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortcutKeysLoader.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/path/DesktopAppPathProvider.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/path/DesktopUserDataPathProvider.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/FilesPreviewView.kt, composeApp/src/desktopMain/kotlin/org/openqa/selenium/manager/SeleniumManager.kt
=> :bug: Fix code style issues

composeApp/src/commonMain/kotlin/com/crosspaste/sync/DeviceListener.kt, composeApp/src/commonMain/kotlin/com/crosspaste/sync/DeviceManager.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/NearbyDevicesView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/SearchNearByDevices.kt
=> :hammer: Migrate state variables to StateFlow in DeviceManager

composeApp/src/commonMain/kotlin/com/crosspaste/net/exception/ExceptionHandler.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/plugin/ClientDecryptPlugin.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/plugin/ServerEncryptPluginFactory.kt
=> :bug: Disable encryption on error response

composeApp/src/commonMain/kotlin/com/crosspaste/presist/FileInfoTree.kt
=> :bug: Fix FileInfoTree serialization issue on iOS

composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/PasteboardScreen.desktop.kt
=> :lipstick: Auto-scroll pasteboard list to latest item

composeApp/src/commonMain/kotlin/com/crosspaste/platform/Platform.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/AboutContentView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/Counter.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/CustomTextField.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/AddDeviceManuallyView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceDetailContentView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/NetSettingsContentView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/PasteboardSettingsContentView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/SetStoragePathView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/SettingsContentView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/StoreSettingsContentView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/ExpandView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/devices/DeviceConnectView.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/devices/DevicesScreen.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/settings/NetSettingsView.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/settings/PasteboardSettingsView.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/settings/SettingsScreen.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/settings/StoreSettingsView.desktop.kt
=> :lipstick: Enhance UI contrast in device and settings screen

composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/SetStoragePathView.kt
=> :bug: Fix storage migration error where multi-language conversion was incorrect

composeApp/src/commonMain/kotlin/com/crosspaste/paste/PasteMenuService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/paste/DesktopPasteMenuService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/ColorPreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/FilesPreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/HtmlToImagePreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/ImagesPreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteSpecificPreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/RtfToImagePreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/TextPreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/UrlPreviewView.kt
=> :sparkles: Add click-to-copy feature for pasteboard

composeApp/src/commonMain/composeResources/drawable/bell.svg, composeApp/src/commonMain/kotlin/com/crosspaste/config/AppConfig.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/BaseIcon.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/MainSettingsView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/sound/DesktopSoundService.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/BaseIcon.desktop.kt, composeApp/src/desktopMain/resources/i18n/en.properties, composeApp/src/desktopMain/resources/i18n/es.properties, composeApp/src/desktopMain/resources/i18n/jp.properties, composeApp/src/desktopMain/resources/i18n/zh.properties
=> :sparkles: Add toggle switch for sound effects

composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/Counter.kt
=> :bug: Add padding to Counter component UI

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppEnv.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/AppEnvUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppInfoFactory.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/TabsView.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/app/AppInfoFactoryTest.kt
=> :sparkles: Support Beta AppEnv to enable mobile beta version public testing

composeApp/src/commonMain/kotlin/com/crosspaste/ui/CrossPasteTheme.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/CustomTextField.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/PasteDialog.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/PasteTitleView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/AddDeviceManuallyView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/QRContentView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/ExpandView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/PasteTooltipIconView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/devices/DeviceConnectView.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteDetailInfoView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/PasteSearchView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/SearchInputView.kt
=> :lipstick: Enhance UI components visibility and theming

composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/CustomTextField.kt
=> :sparkles: Add placeholder and leadingIcon to DefaultTextField

CHANGELOG.md, README.md, README.zh-CN.md
=> :memo: Update changelog

composeApp/src/commonMain/kotlin/com/crosspaste/ui/AboutContentView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/Counter.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/LanguageSettingItemView.kt
=> :lipstick: Increase touch targets size according to Google Play pre-launch report

composeApp/src/commonMain/kotlin/com/crosspaste/ui/CrossPasteTheme.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/CustomTextField.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceVerifyView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/TokenView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteDetailInfoView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteMenuView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/SearchInputView.kt
=> :lipstick: Improve UI contrast ratios based on Google Play pre-launch report

composeApp/src/commonMain/kotlin/com/crosspaste/config/AppConfig.kt
=> :bug: Support automatic type conversion in config copying to accommodate different config storage

composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/ThemeSegmentedControl.kt
=> :bug: Incorrect background color of contrast button

composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/CrossPasteGrantAccessibilityPermissions.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/AddDeviceManuallyView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceDetailContentView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceStateView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/NearbyDeviceView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/SyncDeviceView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/theme/CrossPasteTheme.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/ColorUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/devices/DeviceConnectView.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/devices/SyncDeviceView.desktop.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteDetailInfoView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteMenuView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/search/SearchInputView.kt
=> 💄  adaptive status colors based on background

composeApp/src/commonMain/kotlin/com/crosspaste/ui/model/PasteSearchViewModel.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteMenuView.kt
=> :bug: Prevent refresh when favoriting pasteboard in search window

composeApp/src/commonMain/kotlin/com/crosspaste/notification/MessageType.kt, composeApp/src/commonMain/kotlin/com/crosspaste/notification/ToastManager.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/ToastView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindowContent.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopToastManager.kt
=> :lipstick: Adaptive notification colors based on background

composeApp/src/desktopMain/kotlin/com/crosspaste/log/DesktopCrossPasteLogger.kt
Suppressing jmDNS logs unless debug mode is enabled
close #2319
=> :bug: The log files can sometimes be very large

composeApp/src/commonMain/kotlin/com/crosspaste/notification/MessageType.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/BaseColor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/Counter.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/base/ToastView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceBarView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/QRContentView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/theme/CrossPasteTheme.kt
=> :bug: Improve Counter component contrast ratio for better accessibility

composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/PasteboardScreen.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/PasteboardScreen.desktop.kt
=> :hammer: Add openTopBar parameter to PasteboardScreen for supporting TopBar expansion on mobile

composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteSpecificPreviewView.kt
=> :bug: Ensure UI updates correctly when Realm object state changes

composeApp/src/commonMain/kotlin/com/crosspaste/utils/FileUtils.kt
=> :bug: Catch exceptions thrown by existFile

composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceDetailContentView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/ThemeSegmentedControl.kt
=> :hammer: Remove unused commented code

composeApp/src/commonMain/kotlin/com/crosspaste/realm/RealmManagerFactory.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/realm/DesktopRealmManagerFactory.kt
=> :hammer: Refactor RealmManagerFactory to allow custom factory implementation for other platforms

composeApp/src/commonMain/kotlin/com/crosspaste/CrossPasteModule.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/DesktopCrossPasteModule.kt
=> :hammer: Implement dependency injection by modules

composeApp/src/commonMain/kotlin/com/crosspaste/net/clientapi/SyncClientApi.kt, composeApp/src/commonMain/kotlin/com/crosspaste/net/routing/SyncRouting.kt, composeApp/src/commonMain/kotlin/com/crosspaste/sync/SyncHandler.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/PullFileTaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/PullIconTaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/task/TaskExecutor.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/LanguageSettingItemView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/ControlUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/DateUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/TaskUtils.kt, composeApp/src/commonMain/kotlin/com/crosspaste/utils/ToolUtils.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/utils/ControlUtils.desktop.kt
=> :hammer: Add utility method to get current timestamp

composeApp/src/commonMain/kotlin/com/crosspaste/utils/CryptographyUtils.kt
=> :hammer: Extract common signature logic in CryptographyUtils

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppLaunch.kt, composeApp/src/commonMain/kotlin/com/crosspaste/app/AppLock.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppLaunch.kt, composeApp/src/desktopTest/kotlin/com/crosspaste/app/AppLockTest.kt
=> :hammer: Refactor AppLaunch to improve mobile usability

composeApp/src/commonMain/kotlin/com/crosspaste/i18n/Copywriter.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/i18n/I18n.kt
=> :sparkles: Add dynamic parameter formatting support for i18n API

composeApp/src/commonMain/kotlin/com/crosspaste/image/coil/GenerateImageFetcher.kt, composeApp/src/commonMain/kotlin/com/crosspaste/image/coil/ImageItems.kt, composeApp/src/commonMain/kotlin/com/crosspaste/image/coil/ImageLoaders.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/paste/GenerateImageView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/DesktopCrossPasteModule.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/HtmlToImageDetailView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/RtfToImageDetailView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/HtmlToImagePreviewView.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/RtfToImagePreviewView.kt
=> :bug: Standardize preview image sizes using default screen density

composeApp/src/desktopMain/resources/crosspaste-version.properties
=> :bookmark: Update version to 1.1.1

composeApp/src/commonMain/kotlin/com/crosspaste/app/AppLock.kt, composeApp/src/commonMain/kotlin/com/crosspaste/app/AppLockState.kt, composeApp/src/commonMain/kotlin/com/crosspaste/app/GeneralAppLockState.kt, composeApp/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppLaunch.kt
=> :hammer: Change AppLockState to interface to allow extension by other platforms

composeApp/src/commonMain/kotlin/com/crosspaste/ui/devices/NearbyDeviceView.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/model/MarketingPasteDataViewModel.kt, composeApp/src/commonMain/kotlin/com/crosspaste/ui/settings/NetSettingsContentView.kt
=> :bug: Fix iOS build failure due to missing encodeToString import

README.md, README.zh-CN.md, app/src/commonMain/kotlin/com/crosspaste/paste/PasteCollector.kt, app/src/desktopTest/kotlin/com/crosspaste/db/secure/MemorySecureIO.kt, app/src/desktopTest/kotlin/com/crosspaste/net/SyncTest.kt, doc/en/Concepts.md, doc/zh/Concepts.md
=> :bug: Remove remaining realm information from the project

app/src/commonMain/sqldelight/com/crosspaste/db/PasteDatabase.sq
=> :zap: Add index for pasteboard data

app/src/commonMain/kotlin/com/crosspaste/db/paste/PasteDao.kt, app/src/commonMain/kotlin/com/crosspaste/paste/CurrentPaste.kt, app/src/commonMain/kotlin/com/crosspaste/paste/PasteCollector.kt, app/src/commonMain/kotlin/com/crosspaste/task/Html2ImageTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/task/PullFileTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/task/PullIconTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/task/Rtf2ImageTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/task/SyncPasteTaskExecutor.kt, app/src/commonMain/sqldelight/com/crosspaste/db/PasteDatabase.sq
=> :bug: Fix the issue of failing to clean up pasteboard files

app/src/commonMain/kotlin/com/crosspaste/task/SyncPasteTaskExecutor.kt
=> :bug: Single device sync failure triggers unnecessary re-sync of all connected devices

app/src/commonMain/kotlin/com/crosspaste/exception/ErrorCode.kt
=> :bug: Fix ErrorCode code style warnings

app/src/commonMain/kotlin/com/crosspaste/db/paste/PasteDao.kt, app/src/commonMain/kotlin/com/crosspaste/task/CleanPasteTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/utils/DateUtils.kt
=> :hammer: Extract nowInstant() method to improve testability

app/src/commonMain/kotlin/com/crosspaste/db/paste/PasteDao.kt
1. Fix issue where exceptions prevented subsequent queries
2. Add support for prefix matching
close #2463
=> :bug: Enhance pasteboard search functionality

app/src/commonMain/kotlin/com/crosspaste/notification/NotificationManager.kt
=> :hammer: Support null duration in sendNotification API

app/src/commonMain/kotlin/com/crosspaste/task/SyncPasteTaskExecutor.kt
- Split doExecuteTask into multiple smaller functions with single responsibilities
- Create dedicated functions for sync handler filtering, task creation and execution
- Extract error handling logic into separate methods
- Improve null value handling flow
- Enhance code readability and maintainability
close #2476
=> :sparkles: Reduce complexity of SyncPasteTaskExecutor

app/src/commonMain/kotlin/com/crosspaste/notification/Toast.kt, app/src/commonMain/kotlin/com/crosspaste/notification/ToastManager.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/ToastListView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/ToastView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindowContent.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopNotificationManager.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopToastManager.kt
=> :sparkles: Notification bar supports displaying multiple messages

app/src/commonMain/kotlin/com/crosspaste/ui/base/DialogView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/TokenView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindowContent.kt
=> :lipstick: Create DialogView and TokenView to make the overall interface composition clearer

app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteMenuView.kt
=> :bug: Fix the issue where the pasteboard favorites interface doesn't respond in a timely manner

app/src/commonMain/kotlin/com/crosspaste/exception/PasteException.kt, app/src/commonMain/kotlin/com/crosspaste/task/SyncPasteTaskExecutor.kt
=> :bug: Avoid retrying when application sync is blocked

app/src/commonMain/kotlin/com/crosspaste/notification/Message.kt, app/src/commonMain/kotlin/com/crosspaste/notification/NotificationManager.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/ToastView.kt, app/src/commonMain/kotlin/com/crosspaste/utils/DispatcherUtils.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopNotificationManager.kt
=> :bug: Notification messages should be debounced based on content

app/src/commonMain/kotlin/com/crosspaste/app/AppControl.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceDetailContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppControl.kt
=> :hammer: Enhance device sync control with improved conditional checks

app/src/commonMain/kotlin/com/crosspaste/net/plugin/ClientDecryptPlugin.kt
=> :bug: Fix a bug in the decryption plugin where decryption might terminate before data is fully prepared

app/src/commonMain/kotlin/com/crosspaste/paste/item/ImagesPasteItem.kt, app/src/commonMain/kotlin/com/crosspaste/task/PullFileTaskExecutor.kt
=> :bug: Fix the bug that generates ImagesPasteItem bound to local paths

app/src/commonMain/kotlin/com/crosspaste/image/GenerateImageService.kt, app/src/commonMain/kotlin/com/crosspaste/image/coil/AppSourceFetcher.kt, app/src/commonMain/kotlin/com/crosspaste/image/coil/FaviconFetcher.kt, app/src/commonMain/kotlin/com/crosspaste/image/coil/FileExtFetcher.kt, app/src/commonMain/kotlin/com/crosspaste/image/coil/GenerateImageFetcher.kt, app/src/commonMain/kotlin/com/crosspaste/image/coil/ImageLoaders.kt, app/src/commonMain/kotlin/com/crosspaste/image/coil/UserImageFetcher.kt, app/src/commonMain/kotlin/com/crosspaste/task/Html2ImageTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/task/PullIconTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/task/Rtf2ImageTaskExecutor.kt, app/src/desktopMain/kotlin/com/crosspaste/DesktopCrossPasteModule.kt
=> :zap: Optimize Coil fetch implementation

app/src/commonMain/kotlin/com/crosspaste/db/paste/PasteDao.kt, app/src/commonMain/sqldelight/com/crosspaste/db/PasteDatabase.sq
=> :sparkles: Support searching based on source and filename

app/src/commonMain/kotlin/com/crosspaste/db/paste/PasteDao.kt
=> :zap: Automatically clean up failed pasteboard acquisitions

app/src/commonMain/kotlin/com/crosspaste/task/TaskExecutor.kt, app/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt
1. Add concurrency control
2. Support resource release
close #2530
=> :zap: Improve TaskExecutor implementation

app/src/commonMain/kotlin/com/crosspaste/paste/DefaultPasteSyncProcessManager.kt, app/src/desktopMain/kotlin/com/crosspaste/config/DefaultConfigManager.kt
=> :bug: Fix the issue where MutableMap doesn't support computeIfAbsent on iOS

app/src/commonMain/kotlin/com/crosspaste/app/AppFileChooser.kt, app/src/commonMain/kotlin/com/crosspaste/app/AppWindowManager.kt, app/src/commonMain/kotlin/com/crosspaste/paste/PasteExportParam.kt, app/src/commonMain/kotlin/com/crosspaste/paste/PasteExportParamFactory.kt, app/src/commonMain/kotlin/com/crosspaste/paste/PasteExportService.kt, app/src/commonMain/kotlin/com/crosspaste/paste/PasteImportParam.kt, app/src/commonMain/kotlin/com/crosspaste/paste/PasteImportParamFactory.kt, app/src/commonMain/kotlin/com/crosspaste/paste/PasteImportService.kt, app/src/commonMain/kotlin/com/crosspaste/ui/paste/PasteExportContentView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/paste/PasteImportContentView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/settings/StoreSettingsContentView.kt, app/src/commonMain/kotlin/com/crosspaste/utils/CompressUtils.kt, app/src/desktopMain/kotlin/com/crosspaste/DesktopCrossPasteModule.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppFileChooser.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortKeysAction.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/DesktopPasteExportParam.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/DesktopPasteExportParamFactory.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/DesktopPasteImportParam.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/DesktopPasteImportParamFactory.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindow.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/MacTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/WindowsTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopNotificationManager.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/DesktopSettingsViewProvider.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/SetStoragePathView.kt, app/src/desktopMain/kotlin/com/crosspaste/utils/CompressUtils.desktop.kt
=> :hammer: Refactor import/export implementation to facilitate mobile reuse

app/src/commonMain/kotlin/com/crosspaste/paste/plugin/process/FilesToImagesPlugin.kt
=> :bug: Fix incorrect basePath setting when copying SVG and other pasteboard content

app/src/commonMain/kotlin/com/crosspaste/ui/base/AppSourceIcon.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/DefaultPasteTypeIcon.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/IconView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/PasteFileIcon.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/PasteHtmlOrRtfIcon.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/PasteTypeIconView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/PasteUrlIcon.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteDetailInfoView.kt
=> :hammer: Refactor pasteboard type icons

app/src/commonMain/kotlin/com/crosspaste/ui/model/PasteSearchViewModel.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/model/PasteSelectionViewModel.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/SearchListView.kt
=> :bug: Search window cursor position shouldn't reset when loading more results

app/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncManager.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/DialogButtonsView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/PasteDialog.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceBarView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceVerifyView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/DevicesView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/SetStoragePathView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/ShortcutKeysContentView.kt
=> :lipstick: Optimized Dialog UI effects

app/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceBarView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceVerifyView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/devices/DeviceConnectContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/devices/SyncDeviceContentView.kt
=> :bug: Text and icons in the device bar should adapt to background color changes

app/src/commonMain/kotlin/com/crosspaste/ui/ScreenType.kt
=> :sparkles: Add name property to ScreenType

app/src/commonMain/kotlin/com/crosspaste/ui/HomeMenuView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/MenuView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/settings/CleanTimeMenuView.kt
=> :lipstick: Enhanced date picker UI

app/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncManager.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/PasteDialog.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/PasteDialogFactory.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/DevicesView.kt, app/src/desktopMain/kotlin/com/crosspaste/DesktopCrossPasteModule.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopPasteDialog.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopPasteDialogFactory.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/SetStoragePathView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/ShortcutKeysContentView.kt
=> :hammer: Abstract PasteDialog to allow different implementations for desktop and mobile

app/src/commonMain/kotlin/com/crosspaste/ui/settings/NetSettingsContentView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/settings/PasteboardSettingsContentView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/settings/StoreSettingsContentView.kt
=> :lipstick: Add support for extended configuration options

app/src/commonMain/kotlin/com/crosspaste/ui/base/PasteTitleView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/PasteTypeIconView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/SingleFilePreviewView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/SingleImagePreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/ColorPreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/ComplexPreviewContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/FilesPreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/HtmlToImagePreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/ImagesPreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteMenuView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/RtfToImagePreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/SimplePreviewContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/TextPreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/UrlPreviewView.kt
=> :lipstick: Improved pasteboard display effects

app/src/commonMain/kotlin/com/crosspaste/ui/base/ToastView.kt
=> :lipstick: Add text alignment and line height to ToastView title

app/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceVerifyView.kt
=> :bug: Resolve FocusRequester initialization error in DeviceVerifyView

app/src/commonMain/kotlin/com/crosspaste/db/paste/PasteData.kt, app/src/commonMain/kotlin/com/crosspaste/ui/model/GeneralPasteDataViewModel.kt, app/src/commonMain/kotlin/com/crosspaste/ui/model/PasteSearchViewModel.kt
=> :bug: Prevent displaying invalid PasteData

app/src/commonMain/kotlin/com/crosspaste/db/paste/PasteData.kt, app/src/commonMain/kotlin/com/crosspaste/image/AbstractFaviconLoader.kt, app/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncHandler.kt, app/src/commonMain/kotlin/com/crosspaste/task/PullFileTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/task/TaskExecutor.kt, app/src/desktopMain/kotlin/com/crosspaste/platform/linux/api/WMCtrl.kt, app/src/desktopMain/kotlin/com/crosspaste/plugin/office/OfficeHtmlPlugin.kt, app/src/desktopMain/kotlin/com/crosspaste/rendering/DesktopHtmlRenderingService.kt
=> :hammer: Optimize Kotlin code using scope functions and null-safety operators

app/src/commonMain/kotlin/com/crosspaste/ui/devices/NotFoundNearByDevices.kt, app/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/PasteEmptyScreenView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/SearchInputView.kt
=> :lipstick: Improve font styles for empty screen prompts and paste type selection area

app/src/commonMain/kotlin/com/crosspaste/app/AppTokenApi.kt, app/src/commonMain/kotlin/com/crosspaste/app/AppTokenService.kt, app/src/commonMain/kotlin/com/crosspaste/net/clientapi/SyncClientApi.kt, app/src/commonMain/kotlin/com/crosspaste/net/routing/SyncRouting.kt, app/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncHandler.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppTokenService.kt
=> :sparkles: Automatically close token and hide interface after successful connection

app/src/commonMain/kotlin/com/crosspaste/ui/base/ToastView.kt
=> :bug: Fix inconsistent icon sizes in ToastView

app/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceDetailContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/TabsView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/devices/DeviceConnectContentView.kt
=> :hammer: Enhance device detail page and tab styling

app/src/commonMain/kotlin/com/crosspaste/app/AppSize.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/ToastView.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppSize.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/DesktopPasteMenuService.kt
=> :lipstick: improve UI layout for toastview messages

app/src/commonMain/kotlin/com/crosspaste/ui/base/DialogButtonsView.kt
=> :lipstick: Center align button text in dialog buttons

app/src/commonMain/kotlin/com/crosspaste/paste/plugin/process/MultiFilesPlugin.kt, app/src/commonMain/kotlin/com/crosspaste/paste/plugin/process/MultiImagesPlugin.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopImageTypePlugin.kt
=> :bug:fixed issue with clipboard image paste monitoring on linux

app/src/commonMain/kotlin/com/crosspaste/sync/MarketingSyncHandler.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppControl.kt
=> :bug: Fix all compilation warnings

app/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncManager.kt, app/src/commonMain/kotlin/com/crosspaste/sync/MarketingSyncManager.kt, app/src/commonMain/kotlin/com/crosspaste/sync/SyncManager.kt, app/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt
=> :hammer: Change SyncManager to explicit lifecycle control

app/src/commonMain/kotlin/com/crosspaste/info/PasteInfo.kt, app/src/commonMain/kotlin/com/crosspaste/net/clientapi/ClientApiResult.kt, app/src/commonMain/kotlin/com/crosspaste/net/exception/ExceptionHandler.kt, app/src/commonMain/kotlin/com/crosspaste/paste/CurrentPaste.kt, app/src/commonMain/kotlin/com/crosspaste/paste/PasteCollector.kt, app/src/commonMain/kotlin/com/crosspaste/paste/PasteExportService.kt, app/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncHandler.kt, app/src/commonMain/kotlin/com/crosspaste/sync/MarketingNearbyDeviceManager.kt, app/src/commonMain/kotlin/com/crosspaste/sync/QRCodeGenerator.kt, app/src/commonMain/kotlin/com/crosspaste/task/CleanTaskTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/task/PullIconTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/utils/ColorUtils.kt, app/src/desktopMain/kotlin/com/crosspaste/image/DesktopImageWriter.kt, app/src/desktopMain/kotlin/com/crosspaste/platform/linux/api/WMCtrl.kt, app/src/desktopMain/kotlin/com/crosspaste/rendering/ChromeServiceServiceModule.kt, app/src/desktopMain/kotlin/com/crosspaste/utils/CodecsUtils.desktop.kt
=> :hammer: Convert verbose if-else returns to expression form

app/src/commonMain/kotlin/com/crosspaste/app/RatingPromptManager.kt, app/src/commonMain/kotlin/com/crosspaste/config/SimpleConfig.kt, app/src/commonMain/kotlin/com/crosspaste/config/SimpleConfigFactory.kt, app/src/commonMain/kotlin/com/crosspaste/sync/GeneralNearbyDeviceManager.kt, app/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncHandler.kt, app/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncManager.kt, app/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, app/src/desktopMain/kotlin/com/crosspaste/DesktopCrossPasteModule.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopRatingPromptManager.kt, app/src/desktopMain/kotlin/com/crosspaste/config/DesktopConfigManager.kt, app/src/desktopMain/kotlin/com/crosspaste/config/DesktopSimpleConfig.kt, app/src/desktopMain/kotlin/com/crosspaste/config/DesktopSimpleConfigFactory.kt, app/src/desktopTest/kotlin/com/crosspaste/i18n/GlobalCopywriterTest.kt
=> :sparkles: Create RatingPromptManager for callbacks on important operations

README.md, README.zh-CN.md
=> :memo: Add DeepWiki link to README

app/src/desktopMain/resources/crosspaste-version.properties
=> :bookmark: Update version to 1.1.2

.github/workflows/build-release.yml, conveyor.conf
=> :construction_worker: Update conveyor action to v17.0

.github/workflows/build-release.yml, app/build.gradle.kts
=> :bug: Fix missing dylib files in build output

.github/workflows/build-release.yml
=> :bug: Fix incorrect dylib verification path

app/script/win_start.bat, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppRestartService.kt
=> :bug: Fix Windows application restart service

app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppRestartService.kt, app/src/desktopMain/kotlin/com/crosspaste/path/DesktopMigration.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/SetStoragePathView.kt, app/src/desktopMain/resources/i18n/en.properties, app/src/desktopMain/resources/i18n/es.properties, app/src/desktopMain/resources/i18n/ja.properties, app/src/desktopMain/resources/i18n/zh.properties
=> :bug: Fix logical errors in data migration checks

app/script/win_start.bat, app/src/desktopMain/kotlin/com/crosspaste/path/DesktopMigration.kt
=> :bug: Fix process termination waiting issue in Windows startup script

app/src/commonMain/kotlin/com/crosspaste/db/DriverFactory.kt, app/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, app/src/desktopMain/kotlin/com/crosspaste/db/DesktopDriverFactory.kt
=> :bug: Close database driver before data migration

app/src/commonMain/kotlin/com/crosspaste/ui/base/MenuView.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppSize.kt
=> :bug: Fix the issue of incomplete Windows right-click menu display

app/src/commonMain/kotlin/com/crosspaste/db/paste/PasteDao.kt, app/src/commonMain/kotlin/com/crosspaste/paste/item/PasteFiles.kt
=> :bug: Fix file deletion issue in storage directory copying caused by identical hash values

app/src/desktopMain/kotlin/com/crosspaste/ui/TabsView.kt
=> :bug: Fix the issue where the selected underline in TabsView does not match the text length

app/src/commonMain/kotlin/com/crosspaste/ui/base/MenuView.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppSize.kt
=> :bug: Fix issue where Window right-click menu height doesn't account for padding

app/build.gradle.kts, app/src/commonMain/kotlin/com/crosspaste/db/paste/PasteDao.kt, app/src/commonMain/kotlin/com/crosspaste/paste/PasteImportService.kt, app/src/commonMain/kotlin/com/crosspaste/paste/SearchContentService.kt, app/src/commonMain/kotlin/com/crosspaste/ui/model/GeneralPasteSearchViewModel.kt, app/src/commonMain/kotlin/com/crosspaste/ui/model/MarketingPasteSearchViewModel.kt, app/src/commonMain/kotlin/com/crosspaste/ui/model/PasteSearchViewModel.kt, app/src/desktopMain/kotlin/com/crosspaste/DesktopCrossPasteModule.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/DesktopSearchContentService.kt, gradle/libs.versions.toml
=> :zap: Enhance search matching by preprocessing text with ICU4J tokenizer

app/src/commonMain/kotlin/com/crosspaste/net/PasteServer.kt, app/src/desktopMain/kotlin/com/crosspaste/net/DesktopPasteServer.kt, app/src/desktopMain/kotlin/com/crosspaste/net/exception/DesktopExceptionHandler.kt
Additionally optimized the method for checking port conflict exceptions
close #2710
=> :bug: Specify parentCoroutineContext to prevent application crash during port conflicts

app/src/commonMain/kotlin/com/crosspaste/ui/base/DialogButtonsView.kt
=> :lipstick: Add vertical alignment to DialogButtonsView button row

app/src/desktopMain/kotlin/com/crosspaste/ui/search/SearchInputView.kt
=> :lipstick: Add leadingIcon and trailingIcon to search Input

.github/dependabot.yml
=> :construction_worker: Dependabot ignore alpha dev version

app/src/commonMain/kotlin/com/crosspaste/db/paste/PasteDao.kt
=> :zap: Optimize createSearchPasteQuery function

app/src/commonMain/kotlin/com/crosspaste/ui/base/ExpandViewProvider.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopExpandViewProvider.kt
=> :bug: Fix ExpandView interface compilation issues on Android Compose

app/src/commonMain/kotlin/com/crosspaste/ui/settings/ThemeSegmentedControl.kt
=> :bug: Correct background and icon color contrast issues

app/src/commonMain/kotlin/com/crosspaste/ui/base/ToastView.kt
=> :lipstick: Change toast message textAlign to TextAlign.Justify

app/build.gradle.kts, app/jbr.yaml
=> :construction_worker: Upgrade JBR to 21.0.7b968.13

app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppStartUpService.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppUpdateService.kt, app/src/desktopMain/kotlin/com/crosspaste/image/DesktopFaviconLoader.kt, app/src/desktopMain/kotlin/com/crosspaste/module/AbstractModuleLoader.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopImageTypePlugin.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopUrlTypePlugin.kt, app/src/desktopMain/kotlin/com/crosspaste/platform/linux/FreedesktopUtils.kt, app/src/desktopMain/kotlin/com/crosspaste/platform/linux/LinuxPlatform.kt, app/src/desktopMain/kotlin/com/crosspaste/platform/windows/WinProcessUtils.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopUISupport.kt, app/src/desktopMain/kotlin/com/crosspaste/utils/DeviceUtils.desktop.kt, app/src/desktopMain/kotlin/com/crosspaste/utils/UrlUtils.desktop.kt, app/src/desktopMain/kotlin/org/openqa/selenium/manager/SeleniumManager.kt
=> :hammer: Migrate deprecated APIs for JDK 21 compatibility

app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/app/LinuxAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/app/MacAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/app/WinAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindowContent.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/MacTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/WindowsTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteDetailView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/PasteSearchView.kt, app/src/desktopTest/kotlin/com/crosspaste/app/TestWindowManager.kt
=> :hammer: Obtain DesktopAppSize directly through dependency injection framework

app/src/desktopMain/kotlin/com/crosspaste/DesktopCrossPasteModule.kt, app/src/desktopMain/kotlin/com/crosspaste/i18n/I18n.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopUISupport.kt, app/src/desktopTest/kotlin/com/crosspaste/i18n/GlobalCopywriterTest.kt
=> :hammer: Rename GlobalCopywriter related classes, add platform prefix for better distinction

app/build.gradle.kts, app/src/desktopTest/kotlin/com/crosspaste/db/TestDriverFactory.kt, app/src/desktopTest/kotlin/com/crosspaste/db/sync/SyncRuntimeInfoDaoTest.kt, gradle/libs.versions.toml
=> :white_check_mark: Add unit tests for SyncRuntimeInfoDao reactive flow behavior

README.md, README.zh-CN.md
=> :memo: Add sponsors and GitHub star buttons to README

app/src/commonMain/kotlin/com/crosspaste/config/AppConfig.kt
=> :lipstick: Use blue Sea default theme instead of Grass

README.md, README.zh-CN.md
=> :memo: Replace with official DeepWiki badge for weekly updates

app/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteDetailInfoView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/SearchInputView.kt
=> :bug: Correct search window icon color

app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/TextPreviewView.kt
=> :bug: Revert TextOverflow back to Ellipsis from Clip

app/src/commonMain/kotlin/com/crosspaste/paste/plugin/process/GenerateTextPlugin.kt, app/src/desktopMain/kotlin/com/crosspaste/DesktopModule.kt
=> :sparkles: Auto-generate missing text clipboard from HTML/RTF

app/src/commonMain/kotlin/com/crosspaste/utils/HtmlUtils.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopHtmlTypePlugin.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopUISupport.kt, app/src/desktopMain/kotlin/com/crosspaste/utils/HtmlUtils.desktop.kt
=> :sparkles: Add ensureHtmlCharsetUtf8 to enforce UTF-8 encoding in HTML

app/src/commonMain/kotlin/com/crosspaste/net/plugin/ServerEncryptPluginFactory.kt, app/src/commonMain/kotlin/com/crosspaste/net/routing/SyncRouting.kt, app/src/commonMain/kotlin/com/crosspaste/net/routing/SyncRoutingApi.kt, app/src/commonMain/kotlin/com/crosspaste/paste/PasteExportService.kt, app/src/commonMain/kotlin/com/crosspaste/paste/PasteImportService.kt, app/src/commonMain/kotlin/com/crosspaste/sync/GeneralNearbyDeviceManager.kt, app/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncHandler.kt, app/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncManager.kt, app/src/commonMain/kotlin/com/crosspaste/sync/MarketingNearbyDeviceManager.kt, app/src/commonMain/kotlin/com/crosspaste/sync/MarketingSyncHandler.kt, app/src/commonMain/kotlin/com/crosspaste/sync/MarketingSyncManager.kt, app/src/commonMain/kotlin/com/crosspaste/sync/NearbyDeviceManager.kt, app/src/commonMain/kotlin/com/crosspaste/sync/SyncHandler.kt, app/src/commonMain/kotlin/com/crosspaste/sync/SyncManager.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/ToastListView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/ToastView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/AddDeviceManuallyView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceDetailContentView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/DeviceVerifyView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/DevicesContentView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/DevicesView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/devices/NearbyDeviceView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/paste/PasteExportContentView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/paste/PasteImportContentView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/settings/NetSettingsContentView.kt, app/src/commonMain/kotlin/com/crosspaste/utils/ControlUtils.kt, app/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/devices/DeviceConnectContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/PasteSearchView.kt, app/src/desktopTest/kotlin/com/crosspaste/net/routing/TestSyncRoutingApi.kt
=> :bug: Fix issue where rememberCoroutineScope exits due to partial UI switching

README.md, README.zh-CN.md, doc/en/Roadmap.md, doc/zh/Roadmap.md
=> :memo: Update Readme

app/build.gradle.kts, app/src/commonMain/kotlin/com/crosspaste/app/AppUpdateService.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppUpdateService.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/HomeMenuView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/NewVersionButton.kt, gradle/libs.versions.toml
=> :sparkles:support direct trigger for online upgrade

app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppUpdateService.kt
=> :bug: Handle uncaught exceptions in triggerUpdateCheckUI

app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppUpdateService.kt, app/src/desktopMain/kotlin/com/crosspaste/image/DesktopFaviconLoader.kt, app/src/desktopMain/kotlin/com/crosspaste/module/AbstractModuleLoader.kt, app/src/desktopMain/kotlin/com/crosspaste/net/DesktopClient.kt, app/src/desktopMain/kotlin/com/crosspaste/net/DesktopProxy.kt
=> :sparkles: Create DesktopClient to reuse duplicate code for network requests

app/src/commonMain/kotlin/com/crosspaste/paste/item/HtmlPasteItem.kt, app/src/commonMain/kotlin/com/crosspaste/paste/item/RtfPasteItem.kt, app/src/commonMain/kotlin/com/crosspaste/rendering/RenderingService.kt, app/src/commonMain/kotlin/com/crosspaste/task/Html2ImageTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/task/Rtf2ImageTaskExecutor.kt, app/src/desktopMain/kotlin/com/crosspaste/DesktopModule.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopHtmlTypePlugin.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopRtfTypePlugin.kt, app/src/desktopMain/kotlin/com/crosspaste/rendering/DesktopHtmlRenderingService.kt, app/src/desktopMain/kotlin/com/crosspaste/rendering/DesktopRtfRenderingService.kt
=> :hammer: Change RenderingService to accept PasteData parameter for flexibility

app/src/commonMain/kotlin/com/crosspaste/paste/item/HtmlPasteItem.kt, app/src/commonMain/kotlin/com/crosspaste/paste/item/RtfPasteItem.kt, app/src/commonMain/kotlin/com/crosspaste/serializer/HtmlPasteItemSerializer.kt, app/src/commonMain/kotlin/com/crosspaste/serializer/RtfPasteItemSerializer.kt
=> :bug: Create custom serializers for HtmlPasteItem and RtfPasteItem for legacy version compatibility

app/src/commonMain/kotlin/com/crosspaste/db/paste/PasteDao.kt, app/src/commonMain/kotlin/com/crosspaste/paste/GuidePasteDataService.kt, app/src/commonMain/kotlin/com/crosspaste/paste/plugin/type/ColorTypePlugin.kt, app/src/commonMain/kotlin/com/crosspaste/paste/plugin/type/TextTypePlugin.kt, app/src/commonMain/sqldelight/com/crosspaste/db/PasteDatabase.sq, app/src/desktopMain/kotlin/com/crosspaste/DesktopModule.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/DesktopGuidePasteDataService.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopColorTypePlugin.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopTextTypePlugin.kt, app/src/desktopMain/kotlin/com/crosspaste/rendering/DesktopOpenGraphService.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopUISupport.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/edit/PasteTextEditContentView.kt
=> :bug: Update searchContent, size, and hash when pasteItem is updated

app/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt
=> :bug: Fix Linux tray menu not responding to language switching

app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/app/LinuxAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/app/MacAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/app/WinAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/SearchWindow.kt, app/src/desktopTest/kotlin/com/crosspaste/app/TestWindowManager.kt
=> :hammer: Unify search window to reuse single instance

app/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppSize.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteWindows.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/MenuHelper.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/SearchWindow.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/PasteSummaryView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/center/CenterSearchWindowContent.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/center/SearchInputView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/center/SearchListView.kt
=> :bug: Resolve window display issue with mixed window types on Linux

app/src/commonMain/kotlin/com/crosspaste/ui/theme/AppUIFont.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/center/CenterSearchWindowContent.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/center/SearchFooterView.kt
=> :bug: Fix search footer text color contrast

.github/workflows/claude-code-review.yml, .github/workflows/claude.yml
=> :bug: Improve claude workflow

app/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppTokenService.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/app/LinuxAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/app/MacAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/app/WinAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/listen/DesktopShortKeysAction.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/DesktopPasteMenuService.kt, app/src/desktopMain/kotlin/com/crosspaste/platform/windows/api/User32.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/LinuxTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/MacTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/MainWindow.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/MenuHelper.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/SearchWindow.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/WindowsTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/model/PasteSelectionViewModel.kt, app/src/desktopTest/kotlin/com/crosspaste/app/AppWindowManagerTest.kt, app/src/desktopTest/kotlin/com/crosspaste/app/TestWindowManager.kt
=> :bug: Correct window context reading in app window manager

app/src/desktopMain/kotlin/com/crosspaste/ui/CrossPasteMainWindowContent.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopPasteDialog.kt
=> :lipstick: Adjust dialog width for better display

.github/workflows/claude-code-review.yml
=> :construction_worker: Auto-close Claude Code Review action when PR is closed

app/src/commonMain/kotlin/com/crosspaste/paste/PasteMenuService.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/DesktopPasteMenuService.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/PasteSummaryView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/SidePasteboardContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/ComplexPreviewContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/SimplePreviewContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/center/DetailPasteDataView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/center/SearchFooterView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/center/SearchListView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/side/SideSearchInputView.kt, app/src/desktopMain/resources/i18n/de.properties, app/src/desktopMain/resources/i18n/en.properties, app/src/desktopMain/resources/i18n/es.properties, app/src/desktopMain/resources/i18n/fa.properties, app/src/desktopMain/resources/i18n/fr.properties, app/src/desktopMain/resources/i18n/ja.properties, app/src/desktopMain/resources/i18n/ko.properties, app/src/desktopMain/resources/i18n/zh-hant.properties, app/src/desktopMain/resources/i18n/zh.properties
=> :sparkles: Add hints to side window

app/src/commonMain/kotlin/com/crosspaste/config/AppConfig.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/FontManager.kt, app/src/commonMain/kotlin/com/crosspaste/ui/settings/FontSettingItemView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/theme/CrossPasteTheme.kt, app/src/desktopMain/kotlin/com/crosspaste/DesktopModule.kt, app/src/desktopMain/kotlin/com/crosspaste/config/DesktopAppConfig.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/DesktopFontManager.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/MainSettingsContentView.kt, app/src/desktopMain/resources/i18n/de.properties, app/src/desktopMain/resources/i18n/en.properties, app/src/desktopMain/resources/i18n/es.properties, app/src/desktopMain/resources/i18n/fa.properties, app/src/desktopMain/resources/i18n/fr.properties, app/src/desktopMain/resources/i18n/ja.properties, app/src/desktopMain/resources/i18n/ko.properties, app/src/desktopMain/resources/i18n/zh-hant.properties, app/src/desktopMain/resources/i18n/zh.properties
This pull request introduces a setting that allows users to change the font used in the application interface
=> :sparkles: Add option to change application font

app/src/commonMain/kotlin/com/crosspaste/ui/paste/PasteExportContentView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/settings/StoreSettingsContentView.kt
=> :bug: Fix incorrect RTF file icon assignment

app/src/desktopMain/kotlin/com/crosspaste/i18n/I18n.kt, app/src/desktopTest/kotlin/com/crosspaste/i18n/GlobalCopywriterTest.kt
=> :sparkles: Add fallback to en locale for missing i18n keys

app/src/commonMain/kotlin/com/crosspaste/ui/devices/NearbyDevicesView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/settings/NetSettingsContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/PasteboardContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/SidePasteboardContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteDetailInfoView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/center/SearchListView.kt
=> :bug: Resolve index mismatch in lazy components due to closure issues

app/src/desktopMain/kotlin/com/crosspaste/ui/MainMenuView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/side/SideSearchInputView.kt
=> :bug: Fix tutorial button visibility after UI changes

app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/HtmlSidePreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/RtfSidePreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/TextSidePreviewView.kt, app/src/desktopMain/resources/i18n/de.properties, app/src/desktopMain/resources/i18n/en.properties, app/src/desktopMain/resources/i18n/es.properties, app/src/desktopMain/resources/i18n/fa.properties, app/src/desktopMain/resources/i18n/fr.properties, app/src/desktopMain/resources/i18n/ja.properties, app/src/desktopMain/resources/i18n/ko.properties, app/src/desktopMain/resources/i18n/zh.properties, app/src/desktopMain/resources/i18n/zh_hant.properties
=> :lipstick: Add pasteboard character count text

app/src/commonMain/kotlin/com/crosspaste/paste/item/HtmlPasteItem.kt, app/src/commonMain/kotlin/com/crosspaste/utils/ColorUtils.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopHtmlTypePlugin.kt, app/src/desktopTest/kotlin/com/crosspaste/utils/HtmlUtilsTest.kt
=> :bug: Fix HTML background storage losing alpha bug and add more unit tests

app/src/desktopMain/kotlin/com/crosspaste/ui/MainWindow.kt
=> :zap: Optimize decoration bar drag effect

app/src/desktopMain/kotlin/com/crosspaste/config/DesktopAppConfig.kt
=> :wrench: Set search window to use side style as default configuration

app/src/desktopMain/kotlin/com/crosspaste/ui/MainMenuView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/MenuHelper.kt
=> :lipstick: Add check for updates menu item to main windows

app/src/desktopMain/kotlin/com/crosspaste/DesktopModule.kt, app/src/desktopMain/kotlin/com/crosspaste/config/DesktopAppConfig.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/AbstractPasteboardService.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/WindowsPasteboardService.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopTextTypePlugin.kt, app/src/desktopMain/kotlin/com/crosspaste/platform/windows/ClipboardFormats.kt, app/src/desktopMain/kotlin/com/crosspaste/platform/windows/GlobalMemoryFlags.kt, app/src/desktopMain/kotlin/com/crosspaste/platform/windows/WindowClipboard.kt, app/src/desktopMain/kotlin/com/crosspaste/platform/windows/api/Kernel32.kt, app/src/desktopMain/kotlin/com/crosspaste/platform/windows/api/User32.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/DesktopSettingsViewProvider.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/WindowsPasteboardSettingsContentView.kt, app/src/desktopMain/resources/i18n/de.properties, app/src/desktopMain/resources/i18n/en.properties, app/src/desktopMain/resources/i18n/es.properties, app/src/desktopMain/resources/i18n/fa.properties, app/src/desktopMain/resources/i18n/fr.properties, app/src/desktopMain/resources/i18n/ja.properties, app/src/desktopMain/resources/i18n/ko.properties, app/src/desktopMain/resources/i18n/zh.properties, app/src/desktopMain/resources/i18n/zh_hant.properties
=> :sparkles: publish cf text fallback for legacy ansi apps

.github/workflows/build-release.yml
=> :construction_worker: Update OSS upload action plugin to prevent timeout issues

.github/workflows/build-release.yml
=> :bug: Split ossutil setup and upload steps in GitHub Actions workflow

app/src/commonMain/kotlin/com/crosspaste/image/AbstractFaviconLoader.kt, app/src/commonMain/kotlin/com/crosspaste/image/AbstractFileExtImageLoader.kt, app/src/commonMain/kotlin/com/crosspaste/image/AbstractThumbnailLoader.kt, app/src/commonMain/kotlin/com/crosspaste/image/GenerateImageService.kt, app/src/commonMain/kotlin/com/crosspaste/task/DeletePasteTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/task/Html2ImageTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/task/OpenGraphTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/task/PullIconTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/task/Rtf2ImageTaskExecutor.kt, app/src/commonMain/kotlin/com/crosspaste/utils/ConcurrentLoader.kt, app/src/commonMain/kotlin/com/crosspaste/utils/StripedMutex.kt, app/src/desktopMain/kotlin/com/crosspaste/image/DesktopIconColorExtractor.kt, app/src/desktopMain/kotlin/com/crosspaste/rendering/DesktopHtmlRenderingService.kt, app/src/desktopMain/kotlin/com/crosspaste/rendering/DesktopOpenGraphService.kt, app/src/desktopMain/kotlin/com/crosspaste/rendering/DesktopRtfRenderingService.kt, app/src/desktopTest/kotlin/com/crosspaste/image/ConcurrentLoaderTest.kt
=> :bug: Resolve mutex lock conflicts in concurrent operations

app/src/desktopMain/kotlin/com/crosspaste/app/WinAppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/image/DesktopFileExtLoader.kt, app/src/desktopMain/kotlin/com/crosspaste/platform/windows/JIconExtract.kt, app/src/desktopMain/kotlin/com/crosspaste/platform/windows/api/User32.kt
=> :zap: Improve Windows icon extraction implementation

app/src/desktopMain/kotlin/com/crosspaste/DesktopModule.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/process/FileToUrlPlugin.kt
=> :sparkles: Add URL extraction from .url shortcut files

app/src/commonMain/kotlin/com/crosspaste/sync/MarketingSyncManager.kt, app/src/commonMain/kotlin/com/crosspaste/ui/model/MarketingPasteData.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/SearchWindow.kt
=> :lipstick: Improve marketing mode configuration

app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/SidePastePreviewItemView.kt
=> :bug: Fix drag and drop file cutting instead of copying to clipboard

.gitignore, i18n_batch_update.sh
=> :sparkles: Add i18n batch addition script

app/src/commonMain/kotlin/com/crosspaste/utils/FileNameNormalizer.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopFilesTypePlugin.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopImageTypePlugin.kt
=> :bug: Handle invalid filename characters when syncing files from other systems to Windows

app/src/desktopMain/kotlin/com/crosspaste/CrossPaste.kt
=> :bug: Use async execution for slow operations during app startup

shared/src/commonMain/kotlin/com/crosspaste/utils/I18nDateTimeFormat.kt
=> :sparkles: Add multi-language support for date/time formatting

.github/workflows/claude-code-review.yml
=> :bug: Prevent workflow loop and restrict review access to authorized users

app/src/commonMain/kotlin/com/crosspaste/clean/CleanScheduler.kt
=> :bug: Improve CleanScheduler resilience and error handling

app/src/commonMain/kotlin/com/crosspaste/paste/DefaultPasteSyncProcessManager.kt, app/src/desktopTest/kotlin/com/crosspaste/paste/DefaultPasteSyncProcessManagerTest.kt, app/src/desktopTest/kotlin/com/crosspaste/paste/PasteSingleProcessImplTest.kt
- Create DefaultPasteSyncProcessManagerTest with 18 test methods (427 lines)
- Create PasteSingleProcessImplTest with 14 test methods (291 lines)
- Test core functionality: process management, task execution, progress tracking
- Add concurrency tests: semaphore limits, thread safety, parallel execution
- Test edge cases: empty tasks, invalid indices, exception handling
- Add performance tests: large datasets (10K tasks), high concurrency (50 operations)
- Verify progress flow updates and monotonicity
- Test boundary conditions: zero tasks, out-of-range indices, duplicate completions
- All 32 tests passing with comprehensive coverage of critical sync components
close #3107
=>  :white_check_mark: Add comprehensive unit tests for DefaultPasteSync ProcessManager and PasteSingleProcessImpl

app/src/commonMain/kotlin/com/crosspaste/utils/FileNameNormalizer.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopFilesTypePlugin.kt, app/src/desktopTest/kotlin/com/crosspaste/utils/FileNameNormalizerTest.kt, app/src/desktopTest/kotlin/com/crosspaste/utils/MurmurHash3Test.kt
=> :hammer: Rewrite all toByteArray calls to encodeToByteArray

app/src/commonMain/kotlin/com/crosspaste/ui/paste/PasteDataScope.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteColorDetailView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteFilesDetailView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteImagesDetailView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteTextDetailView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteUrlDetailView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/center/DetailPasteDataView.kt
=>  :hammer: Optimize PasteDataScope related code

app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/PreSidePreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/SidePreviewView.kt
=>  :bug: Fix PasteShimmer UI in side window

app/src/commonMain/kotlin/com/crosspaste/image/ImageHandler.kt, app/src/commonMain/kotlin/com/crosspaste/rendering/OpenGraphService.kt, app/src/desktopMain/kotlin/com/crosspaste/DesktopModule.kt, app/src/desktopMain/kotlin/com/crosspaste/image/DesktopFileExtLoader.kt, app/src/desktopMain/kotlin/com/crosspaste/image/DesktopImageHandler.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/plugin/type/DesktopImageTypePlugin.kt
=>  :hammer: Rename ImageWriter interface to imageHandler and add read methods

app/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncHandler.kt, app/src/commonMain/kotlin/com/crosspaste/sync/SyncEvent.kt, app/src/commonMain/kotlin/com/crosspaste/sync/SyncPollingManager.kt, app/src/commonMain/kotlin/com/crosspaste/sync/SyncResolver.kt, app/src/desktopMain/kotlin/com/crosspaste/net/DesktopPasteBonjourService.kt
=>  :hammer: Extract independent connection maintenance logic for connected and pending devices

app/src/commonMain/kotlin/com/crosspaste/sync/GeneralSyncManager.kt, app/src/commonMain/kotlin/com/crosspaste/sync/SyncPollingManager.kt, app/src/desktopTest/kotlin/com/crosspaste/sync/GeneralSyncManagerTest.kt
=>  :sparkles: Add dynamic polling interval adjustment to SyncPollingManager

app/build.gradle.kts, app/src/commonMain/kotlin/com/crosspaste/sync/SyncPollingManager.kt, build.gradle.kts, gradle/libs.versions.toml
=>  :hammer: Rewrite SyncPollingManager to use atomic instead of @Volatile for multiplatform support

app/src/commonMain/kotlin/com/crosspaste/app/AppWindowManager.kt, app/src/desktopMain/kotlin/com/crosspaste/app/DesktopAppWindowManager.kt
=> :hammer: Implement Screen navigation and switching in base class for multi-platform reuse

app/src/commonMain/kotlin/com/crosspaste/ui/base/AppSourceIcon.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/PasteFileIcon.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/PasteUrlIcon.kt, app/src/commonMain/kotlin/com/crosspaste/ui/paste/GenerateImageView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/SingleFilePreviewView.kt, app/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/SingleImagePreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/SideAppSourceIcon.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteFilesDetailView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/PasteImagesDetailView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/FilesSidePreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/ImageSidePreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/UrlSidePreviewView.kt
=> Fix UI recomposition for asyncimagepainter state changes

app/src/commonMain/kotlin/com/crosspaste/paste/plugin/process/TextToColorPlugin.kt, app/src/commonMain/kotlin/com/crosspaste/ui/model/MarketingPasteData.kt, app/src/commonMain/kotlin/com/crosspaste/utils/ColorUtils.kt, app/src/commonMain/kotlin/com/crosspaste/utils/CssColor.kt, app/src/desktopTest/kotlin/com/crosspaste/utils/ColorUtilsTest.kt, shared/src/commonMain/kotlin/com/crosspaste/paste/item/ColorPasteItem.kt, shared/src/commonMain/kotlin/com/crosspaste/paste/item/PasteColor.kt
=> :hammer: Rewrite ColorUtils based on ph-css source code

app/src/commonMain/kotlin/com/crosspaste/ui/model/GeneralPasteSearchViewModel.kt, app/src/commonMain/kotlin/com/crosspaste/ui/model/PasteSearchViewModel.kt, app/src/commonMain/kotlin/com/crosspaste/ui/model/SearchParams.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/SidePasteboardContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/SearchTrailingIcon.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/center/SearchListView.kt
=> :zap: Optimize search state management and add throttling for pagination

app/src/desktopMain/kotlin/com/crosspaste/ui/theme/DesktopTheme.kt
=> :hammer: Update theme definitions to use non-deprecated JewelTheme API

app/src/commonMain/kotlin/com/crosspaste/utils/ColorUtils.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/ColorSidePreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/SidePasteLayoutView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/theme/DesktopAppUIColors.kt
=> :sparkles: Add smart contrast color utility for color palette

shared/build.gradle.kts, shared/src/commonMain/kotlin/com/crosspaste/utils/I18nDateTimeFormat.kt, shared/src/commonTest/kotlin/com/crosspaste/utils/DateStyleTest.kt
=> :bug: Remove locale-dependent format directives for cross-platform compatibility

app/src/commonMain/kotlin/com/crosspaste/ui/DebugScreen.kt, app/src/commonMain/kotlin/com/crosspaste/ui/ScreenType.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/DesktopScreenProvider.kt
=> :hammer: Remove Debug UI, debugging now available directly via hot reload

app/src/commonMain/kotlin/com/crosspaste/paste/PasteMenuService.kt, app/src/commonMain/kotlin/com/crosspaste/ui/LocalComposition.kt, app/src/commonMain/kotlin/com/crosspaste/ui/NavigationEvent.kt, app/src/commonMain/kotlin/com/crosspaste/ui/NavigationManager.kt, app/src/commonMain/kotlin/com/crosspaste/ui/Route.kt, app/src/commonMain/kotlin/com/crosspaste/ui/ScreenProvider.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/UISupport.kt, app/src/desktopMain/kotlin/com/crosspaste/DesktopModule.kt, app/src/desktopMain/kotlin/com/crosspaste/paste/DesktopPasteMenuService.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/DesktopLocalComposition.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/DesktopRoute.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/DesktopScreenProvider.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/MainMenuView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/MainWindow.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/DesktopUISupport.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/base/MenuHelper.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/devices/DesktopDeviceScope.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/devices/DesktopSyncScope.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/FilesPreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/ImagesPreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/PasteMenuView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/preview/SimplePreviewContentView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/SidePasteItemView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/search/side/SideSearchInputView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/settings/DesktopSettingsViewProvider.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/tray/LinuxTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/tray/MacTrayView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/tray/WindowsTrayView.kt
=> :hammer: Migrate navigation to event-driven architecture

app/src/commonMain/kotlin/com/crosspaste/image/GenerateImageService.kt, app/src/commonMain/kotlin/com/crosspaste/image/coil/GenerateImageFetcher.kt
=> :bug: Improve image generation service with proper cancellation handling

app/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/UrlBottomSolid.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/UrlBottomSolid.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/UrlSidePreviewView.kt
=> :hammer: Update UrlBottomSolid implementation for multi-platform reuse

app/src/commonMain/kotlin/com/crosspaste/ui/base/CountBadgeAuto.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/FolderIcon.kt, app/src/commonMain/kotlin/com/crosspaste/ui/base/GenerateFileIcon.kt, app/src/commonMain/kotlin/com/crosspaste/ui/paste/preview/SingleFilePreviewView.kt, app/src/commonMain/kotlin/com/crosspaste/utils/ColorUtils.kt, app/src/commonMain/kotlin/com/crosspaste/utils/FileColors.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/FilesDetailView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/detail/ImagesDetailView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/FilesSidePreviewView.kt, app/src/desktopMain/kotlin/com/crosspaste/ui/paste/side/preview/ImageSidePreviewView.kt, shared/src/commonMain/kotlin/com/crosspaste/paste/item/PasteFiles.kt
=> :sparkles: Support rendering files and folders for file pasteboard

shared/build.gradle.kts
=> :bug: Rename native target to nativeApp to avoid conflict with default hierarchy template
